---
metadata:
  env: bali
  costCenter: agglayer

onePasswordSecrets:
  pool-manager: "vaults/myvault/items/myitem"

# Enable to replace $ENV_VARS in the configmap from a Kubernetes secret
# Secret names are derived from onePasswordSecrets keys
envSubstitution:
  enabled: true

# Pod annotations (e.g. ad.datadoghq.com/tags for Datadog)
podAnnotations: {}
# podAnnotations:
#   ad.datadoghq.com/tags: '{"network": "mynetwork"}'

nodeSelector: {}
tolerations: []
initContainers: []
extraVolumes: []
extraVolumeMounts: []
topologySpreadConstraints: []

imagePullSecrets: []

replicaCount: 1

image:
  repository: ghcr.io/0xpolygon/zkevm-pool-manager
  pullPolicy: IfNotPresent
  tag: "0.1.3"
  command: ["/app/zkevm-pool-manager"]
  args: ["run", "--cfg", "/etc/pool-manager/config.toml"]

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8545

resources:
  limits:
    cpu: 1
    memory: 1G
  requests:
    cpu: 1
    memory: 512M

config:
  db:
    user: pool-manager
    password: pool-manager
    name: pool-manager
    host: postgres
    port: 5432
  sender:
    sequencerURL: http://cdk-erigon-sequencer:8123
  server:
    port: 8545
  log:
    environment: development # "production" or "development"
    level: info
  monitor:
    l2NodeURL: http://cdk-erigon-rpc:8123

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
