env: bali

podLabels:
  name: bali-00-erigon
  business_unit: zkevm
  role: integration-network
  partner: Polygon
  network: bali-00-erigon

image:
  repository: ghcr.io/0xpolygon/zkevm-prover
  tag: v8.0.0-RC16-fork.12

isMockProver: false

node: # Used with real Prover only (isMockProver: false)
  machineFamily: c3d # c3d for 1.4TB memory, n2d for 850GB memory.
  cpu: 178           # 178 for c3d, 222 for n2d
  memory: 950Gi      # 950Gi for c3d, 850Gi for n2d

aggregator:
  host: cdk-aggregator-service
  port: 50081

gcpServiceAccount: shared-dev-zkevm-prover-sa@prj-polygonlabs-shared-dev.iam.gserviceaccount.com

gcs:
  bucket: zkevm-prover-files
  version: v8.0.0-rc.9-fork.12

hpa:
  enable: true
  minReplicas: 0
  maxReplicas: 10
