global:
  # tags for identifying/tracking resources
  name: pless-rpc-cardona-idex-05
  host: gcp
  location: europe-west2
  env: cardona
  role: permissionless-node
  team: idex
  p_service: agglayer
  tag: v3

jumphost:
  # We only enable this in non-production environments, right? RIGHT?!?!?
  enabled: true

rpc:
  genesis: idex.genesis.json
  image:
    repository: 0xpolygon/cdk-validium-node
    tag: "0.5.13-cdk.6"

synchronizer:
  genesis: idex.genesis.json
  image:
    repository: 0xpolygon/cdk-validium-node
    tag: "0.5.13-cdk.6"

executor:
  image:
    repository: hermeznetwork/zkevm-prover
    tag: "v4.0.19"

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: dookie
        username: spideyman
        password: booger
        database: state_db
  primary:
    extendedConfiguration: |
      max_connections = 500
    initdb:
      scripts:
        00_init_event_db.sql: |
          CREATE DATABASE event_db;
          \connect event_db
          CREATE TYPE level_t AS ENUM ('emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug');
          CREATE TABLE public.event (
             id BIGSERIAL PRIMARY KEY,
             received_at timestamp WITH TIME ZONE default CURRENT_TIMESTAMP,
             ip_address inet,
             source varchar(32) not null,
             component varchar(32),
             level level_t not null,
             event_id varchar(32) not null,
             description text,
             data bytea,
             json jsonb
          );
        10_init_state_db.sql: |
          CREATE DATABASE state_db;
        20_init_pool_db.sql: |
          CREATE DATABASE pool_db;
        30_init_executor_db.sql: |
          CREATE DATABASE executor_db;
          \connect executor_db
          CREATE SCHEMA state;
          CREATE TABLE state.nodes (hash bytea PRIMARY KEY, data bytea NOT NULL);
          CREATE TABLE state.program (hash bytea PRIMARY KEY, data bytea NOT NULL);
