{{- $combinedJson := .Values.combinedJson | fromJson }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdk.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    AggLayerURL = {{ .Values.config.agglayerURL | quote }}
    AggregatorPrivateKeyPassword = {{ .Values.config.l2.aggregatorPrivateKeyPassword | quote }}
    AggregatorPrivateKeyPath = "/etc/cdk/aggregator.keystore"
    ContractVersions = {{ .Values.config.contractsVersion | quote }}
    ForkId = {{ .Values.config.forkId | int }}
    genesisBlockNumber = {{ $combinedJson.upgradeToULxLyBlockNumber | int }}
    IsValidiumMode = {{ eq .Values.config.isValidium true }}
    L1URL = {{ .Values.config.l1.rpcUrl | quote }}
    L2Coinbase = {{ .Values.config.l2.sequencerAddress | quote }}
    L2URL = {{ .Values.config.l2.rpcURL | quote }}
    PathRWData = {{ .Values.storage.path | quote }}
    polygonBridgeAddr = {{ $combinedJson.polygonZkEVMBridgeAddress | quote }}
    rollupCreationBlockNumber = {{ $combinedJson.createRollupBlockNumber | int }}
    rollupManagerCreationBlockNumber = {{ $combinedJson.upgradeToULxLyBlockNumber | int }}
    RPCURL = {{ .Values.config.l2.rpcURL | quote }}
    SenderProofToL1Addr = {{ .Values.config.l2.agglayerAddress | quote }}
    SequencerPrivateKeyPassword = {{ .Values.config.l2.sequencerPrivateKeyPassword | quote }}
    SequencerPrivateKeyPath =  "/etc/cdk/sequencer.keystore"
    WitnessURL = {{ .Values.config.l2.rpcURL | quote }}

    [L1Config]
    chainId = {{ .Values.config.l1.chainId | int }}
    polygonZkEVMGlobalExitRootAddress = {{ $combinedJson.polygonZkEVMGlobalExitRootAddress | quote }}
    polygonRollupManagerAddress = {{ $combinedJson.polygonRollupManagerAddress | quote }}
    polTokenAddress = {{ $combinedJson.polTokenAddress | quote }}
    polygonZkEVMAddress = {{ $combinedJson.rollupAddress | quote }}
      
    [L2Config]
    GlobalExitRootAddr = {{ $combinedJson.polygonZkEVMGlobalExitRootAddress | quote }}

    [BridgeL2Sync]
    OriginNetwork={{ $combinedJson.rollupID | int }}

    [L1InfoTreeSync]
    SyncBlockChunkSize={{ .Values.config.l1.syncBlockChunkSize | int }}

    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]
          
    [AggSender]
    CertificateSendInterval = {{ .Values.config.aggSender.certificateSendInterval | quote }}
    CheckSettledInterval = {{ .Values.config.aggSender.checkSettledInterval | quote }}
    MaxCertSize = {{ .Values.config.aggSender.maxCertSize | int }}
    SaveCertificatesToFilesPath = {{ .Values.config.aggSender.saveCertificatesToFilesPath | quote }}
  genesis.json: |-
{{ .Values.genesis | indent 4 }}

  sequencer.keystore: |
{{ .Values.config.l2.sequencerKeystore | indent 4 }}

  aggregator.keystore: |
{{ .Values.config.l2.aggregatorKeystore | indent 4 }}
