apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl ((.Files.Glob "config/config.toml.tpl").AsConfig | indent 2) . }}
  genesis: |-
  {{ .Values.genesis | indent 4 }}
