{{- $l1RpcURL := "" }}
{{- $sequencerPrivateKeyPassword := "" }}
{{- $aggregatorPrivateKeyPassword := "" }}

{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace "op-secrets") }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "l1RpcURL") }}
        {{- $l1RpcURL = index $opSecrets.data "l1RpcURL" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "sequencerPrivateKeyPassword") }}
        {{- $sequencerPrivateKeyPassword = index $opSecrets.data "sequencerPrivateKeyPassword" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "aggregatorPrivateKeyPassword") }}
        {{- $aggregatorPrivateKeyPassword = index $opSecrets.data "aggregatorPrivateKeyPassword" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdk.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    AggLayerURL = {{ .Values.config.agglayerURL | quote }}
    AggregatorPrivateKeyPassword = {{ $aggregatorPrivateKeyPassword | quote }}
    AggregatorPrivateKeyPath = "/etc/cdk/aggregator.keystore"
    ContractVersions = {{ .Values.config.contractsVersion | quote }}
    ForkId = {{ .Values.config.forkId | int }}
    genesisBlockNumber = {{ .Values.config.l1.rollupManagerBlockNumber | int }}
    IsValidiumMode = {{ eq .Values.config.isValidium true }}
    L1URL = {{ $l1RpcURL | quote }}
    L2Coinbase = {{ .Values.config.l2.sequencerAddress | quote }}
    L2URL = {{ .Values.config.l2.rpcURL | quote }}
    PathRWData = {{ .Values.storage.path | quote }}
    polygonBridgeAddr = {{ .Values.config.bridgeAddress | quote }}
    rollupCreationBlockNumber = {{ .Values.config.l1.rollupManagerBlockNumber | int }}
    rollupManagerCreationBlockNumber = {{ .Values.config.l1.rollupManagerBlockNumber | int }}
    RPCURL = {{ .Values.config.l2.rpcURL | quote }}
    SenderProofToL1Addr = {{ .Values.config.l2.agglayerAddress | quote }}
    SequencerPrivateKeyPassword = {{ $sequencerPrivateKeyPassword | quote }}
    SequencerPrivateKeyPath =  "/etc/cdk/sequencer.keystore"
    WitnessURL = {{ .Values.config.l2.rpcURL | quote }}

    [L1Config]
    chainId = {{ .Values.config.l1.chainId | int }}
    polygonZkEVMGlobalExitRootAddress = {{ .Values.config.l1.globalExitRootAddress | quote }}
    polygonRollupManagerAddress = {{ .Values.config.l1.rollupManagerAddress | quote }}
    polTokenAddress = {{ .Values.config.l1.polTokenAddress | quote }}
    polygonZkEVMAddress = {{ .Values.config.l1.rollupAddress | quote }}
      
    [L2Config]
    GlobalExitRootAddr = {{ .Values.config.l2.globalExitRootAddress | quote }}

    [BridgeL2Sync]
    OriginNetwork={{ .Values.config.l2.rollupId | int }}

    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]
          
    [AggSender]
    CertificateSendInterval = {{ .Values.config.aggSender.certificateSendInterval | quote }}
    CheckSettledInterval = {{ .Values.config.aggSender.checkSettledInterval | quote }}
  genesis.json: |-
{{ .Values.genesis | indent 4 }}
