apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-succinct-proposer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-succinct-proposer.labels" . | nindent 4 }}
data:
  AGG_PROOF_MODE: {{ .Values.config.aggProofMode | quote }}
  AGGLAYER: {{ .Values.config.agglayer | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  DB_PATH: {{ .Values.storage.path | quote }}
  GRPC_ADDRESS: {{ .Values.config.grpcAddress | quote }}
  L1_BEACON_RPC: ""
  L1_RPC: ""
  L2_NODE_RPC: {{ .Values.config.l2NodeRpcURL | quote }}
  L2_RPC: {{ .Values.config.l2RpcURL | quote }}
  L2OO_ADDRESS: {{ .Values.config.rollupAddress | quote }}
  MAX_CONCURRENT_PROOF_REQUESTS: {{ .Values.config.maxConcurrentProofRequests | quote }}
  MAX_CONCURRENT_WITNESS_GEN: {{ .Values.config.maxConcurrentWitnessGen | quote }}
  METRICS_ENABLED: {{ .Values.config.metricsEnabled | quote }}
  METRICS_PORT: {{ .Values.ports.metrics | quote }}
  NETWORK_PRIVATE_KEY: {{ .Values.config.sp1NetworkPrivateKey | quote }}
  NETWORK_RPC_URL: {{ .Values.config.sp1NetworkRpcURL | quote }}
  OP_SUCCINCT_MOCK: {{ .Values.config.opSuccinctMock | quote }}
  POLL_INTERVAL: {{ .Values.config.pollInterval | quote }}
  PRIVATE_KEY: 0xc797616a567ffd3f7d80f110f4c19900e55258ac2aa96d96ded790e0bd727458
  RANGE_PROOF_INTERVAL: {{ .Values.config.rangeProofInterval | quote }}
  RUST_LOG: {{ .Values.config.rustLog | quote }}
  USE_CACHED_DB: {{ .Values.config.useCachedDB | quote }}
  WITNESS_GEN_TIMEOUT: {{ .Values.config.witnessGenTimeout | quote }}
  OP_SUCCINCT_CONFIG_NAME: {{ .Values.config.opSuccinctConfigName | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
