{{- $l1RpcURL := "" }}
{{- $proposerPrivateKey := "" }}

{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "l1RpcURL") }}
        {{- $l1RpcURL = index $opSecrets.data "l1RpcURL" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "proposerPrivateKey") }}
        {{- $proposerPrivateKey = index $opSecrets.data "proposerPrivateKey" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-succinct-proposer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-succinct-proposer.labels" . | nindent 4 }}
data:
  DB_PATH: {{ .Values.storage.path | quote }}
  DGF_ADDRESS: {{ .Values.config.dgfAddress | quote }}
  L1_RPC: {{ $l1RpcURL | quote }}
  L1_BEACON_RPC: {{ $l1RpcURL | quote }}
  L2_NODE_RPC: {{ .Values.config.l2NodeRpcURL | quote }}
  L2OO_ADDRESS: {{ .Values.config.l2OOAddress | quote }}
  MAX_BLOCK_RANGE_PER_SPAN_PROOF: {{ .Values.config.maxBlockRangePerSpanProof | quote }}
  MAX_CONCURRENT_PROOF_REQUESTS: {{ .Values.config.maxConcurrentProofRequests | quote }}
  MAX_CONCURRENT_WITNESS_GEN: {{ .Values.config.maxConcurrentWitnessGen | quote }}
  METRICS_ENABLED: {{ .Values.config.metricsEnabled | quote }}
  METRICS_PORT: {{ .Values.ports.metrics | quote }}
  OP_SUCCINCT_MOCK: {{ .Values.config.opSuccinctMock | quote }}
  OP_SUCCINCT_SERVER_URL: {{ .Values.config.opSuccinctServerURL | quote }}
  POLL_INTERVAL: {{ .Values.config.pollInterval | quote }}
  PRIVATE_KEY: {{ $proposerPrivateKey | quote }}
  USE_CACHED_DB: {{ .Values.config.useCachedDB | quote }}
  WITNESS_GEN_TIMEOUT: {{ .Values.config.witnessGenTimeout | quote }}
