apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-succinct-proposer.fullname" . }}
  labels:
    {{- include "op-succinct-proposer.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  # StatefulSets require headless services
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "op-succinct-proposer.selectorLabels" . | nindent 4 }}
