{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-succinct-proposer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-succinct-proposer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-succinct-proposer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "op-succinct-proposer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.checks: |
           {
             "openmetrics": {
               "instances": [
                 {
                   "openmetrics_endpoint": "http://%%host%%:{{ .Values.ports.metrics }}/metrics",
                   "metrics": [
                       "op_succinct_proposer.*"
                     ]
                 }
               ]
             }
           }
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "op-succinct-proposer.fullname" . }}-config
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
