apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "deploymentLabels" .}} 
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.commonLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.commonLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{ include "deploymentLabels" .}}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.strategy }}
      strategy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- end }}
          image: {{ .image | quote }}
          imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
          {{- if .command }}
          command: {{ .command | toYaml | nindent 10 }}
          {{- end }}
          {{- if or .env ( and .onePassword .onePassword.InjectorEnvs)  }}
          env:
          {{- if and .onePassword .onePassword.InjectorEnvs  }}
          - name: OP_CONNECT_HOST
            value: {{ .onePassword.connectHost | default "http://onepassword-connect.op:8080" }}
          - name: OP_CONNECT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .onePassword.secretName | default "connect-token" }}
                key: {{ .onePassword.secretKey | default "token" }}
          {{- range $key, $value := .onePassword.InjectorEnvs }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          {{- range .env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- end }}
          {{- if .envFromEnabled }}
          envFrom:
          - configMapRef:
              name: {{ $.Values.name }}-configmap 
          {{- end }}
          {{- if .port }}
          ports:
            - name: http
              containerPort: {{ .port }} 
              protocol: TCP
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
