{{ if .Values.ingress }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.name }}-frontendconfig
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "frontendLabels" .}}
spec:
  redirectToHttps:
    enabled: {{ .Values.httpsRedirect | default "true" }}
{{- end }}
