apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.validator.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "polygon-edge.validatorServiceAccountName" . }}
{{- if .Values.validator.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.validator.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "polygon-edge.labels" (dict "context" . "component" .Values.validator.name "name" .Values.validator.name) | nindent 4 }}
