apiVersion: v1
kind: Service
metadata:
{{- if .Values.validator.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.validator.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "polygon-edge.validator.fullname" . }}
  labels:
    {{- include "polygon-edge.labels" (dict "context" . "component" .Values.validator.name "name" .Values.validator.name) | nindent 4 }}
{{- if .Values.validator.service.labels }}
{{- toYaml .Values.validator.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.validator.service.type }}
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.validator.service.grpc.port }}
    targetPort: {{- if .Values.validator.service.namedTargetPort }} grpc {{- else }} {{ .Values.validator.service.grpc.port }} {{- end }}
    {{- if eq .Values.validator.service.type "NodePort" }}
    nodePort: {{ .Values.validator.service.grpc.nodePort }}
    {{- end }}
  - name: json-rpc
    protocol: TCP
    port: {{ .Values.validator.service.jsonRPC.port }}
    targetPort: {{- if .Values.validator.service.namedTargetPort }} json-rpc {{- else }} {{ .Values.validator.service.jsonRPC.port }} {{- end }}
    {{- if eq .Values.validator.service.type "NodePort" }}
    nodePort: {{ .Values.validator.service.jsonRPC.nodePort }}
    {{- end }}
  selector:
    {{- include "polygon-edge.selectorLabels" (dict "context" . "name" .Values.validator.name) | nindent 4 }}
{{- if eq .Values.validator.service.type "LoadBalancer" }}
{{- if .Values.validator.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.validator.service.loadBalancerIP | quote }}
{{- end }}
{{- if .Values.validator.service.externalIPs }}
  externalIPs: {{ .Values.validator.service.externalIPs }}
{{- end }}
{{- if .Values.validator.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.validator.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- end -}}
{{- with .Values.validator.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
{{- with .Values.validator.service.sessionAffinity }}
  sessionAffinity: {{ . }}
{{- end }}
