env: bali

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: Polygon
  network: mynetwork

replicas: 1
sequencer: true

initContainer:
  image:
    pullPolicy: IfNotPresent
    repository: google/cloud-sdk
    tag: 537.0.0-slim

container:
  image:
    pullPolicy: IfNotPresent
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    tag: v1.101503.1

storage:
  path: /data
  size: 10Gi
  storageClassName: standard

service:
  authrpc:
    port: 8551
  http:
    port: 8545
  ws:
    port: 8546
  metrics:
    port: 7300
  annotations: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}

config:
  extraOptions: {}

  bucket: gs://path/to/bucket/files/*
  path: /etc/op-geth

  syncmode: full
  gcmode: archive

  miner:
    gasLimit: 60000000

  txpool:
    accountqueue: 64
    accountslots: 16
    globalqueue: 1024
    globalslots: 5120

  http:
    api: admin,engine,net,eth,web3,debug,miner

  ws:
    api: admin,engine,net,eth,web3,debug,miner

  rollup:
    sequencerhttp: http://op-geth:8545

  metrics: true

  networkid: 1

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

podSecurityContext:
  fsGroup: 1001
  fsGroupChangePolicy: Always
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 0
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}

tolerations: []

affinity: {}
