# Default values for jumphost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: false

replicaCount: 1

image:
  repository: ubuntu
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

command: ["sleep"]
args: ["infinity"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
