# Configuration for chart-releaser
# https://github.com/helm/chart-releaser

owner: agglayer
git-repo: helm-charts
charts-dir: charts
target-branch: gh-pages
pages-branch: gh-pages
index-path: index.yaml
packages-with-index: true
push: true
generate-release-notes: true
make-release-latest: true
