apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: op-secrets
  annotations:
    "helm.sh/hook": pre-install
spec:
  itemPath: "vaults/{{ .Values.vault }}/items/{{ .Values.item }}"
