---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-secret-reader
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-secret-reader
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-4"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-secret-reader
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-secret-reader
roleRef:
  kind: Role
  name: {{ .Release.Name }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait-op-secrets
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-secret-reader
      restartPolicy: Never
      containers:
      - name: wait-op-secrets
        image: bitnamisecure/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Verifying {{ .Release.Name }} Secret exists..."
          until kubectl get secret {{ .Release.Name }} -n {{ .Release.Namespace }}; do
            echo "Waiting for {{ .Release.Name }} Secret to be created..."
            sleep 5
          done
