apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_AD_BANNER_PROVIDER: "none"
  NEXT_PUBLIC_AD_TEXT_PROVIDER: "none"
  NEXT_PUBLIC_API_HOST: "{{ .Values.backend.ingress.hostname }}"
  # NEXT_PUBLIC_API_PORT: "{{ .Values.backend.port }}"
  NEXT_PUBLIC_API_PROTOCOL: "https"
  NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: "ws"
  NEXT_PUBLIC_APP_HOST: "{{ .Values.frontend.ingress.hostname }}"
  # NEXT_PUBLIC_APP_PORT: "80"
  NEXT_PUBLIC_APP_PROTOCOL: "https"
  NEXT_PUBLIC_DEFI_DROPDOWN_ITEMS: '[{"text": "Polygon zkEVM Bridge", "icon": "swap", "url": "{{ .Values.frontend.swap_url }}" }]'
  NEXT_PUBLIC_NETWORK_ID: "{{ .Values.networkChainId }}"
  NEXT_PUBLIC_NETWORK_NAME: "{{ .Values.networkName }}"
  NEXT_PUBLIC_ROLLUP_L1_BASE_URL: "{{ .Values.frontend.l1ExplorerUrl }}"
  NEXT_PUBLIC_ROLLUP_TYPE: "zkEvm"
  NEXT_PUBLIC_STATS_API_HOST: "https://{{ .Values.stats.ingress.hostname }}"
  NEXT_PUBLIC_TRANSACTION_INTERPRETATION_PROVIDER: "blockscout"
  # NEXT_PUBLIC_USE_NEXT_JS_PROXY: "{{ .Values.frontend.backendExposed }}"
  NEXT_PUBLIC_VISUALIZE_API_HOST: "https://{{ .Values.visualize.ingress.hostname }}"