apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: {{ .Values.namespace }}
data:
  init.sql: |
    {{- range .Values.blockscout.postgres.dbConfigs }}
    CREATE USER {{ .user }} WITH PASSWORD '{{ .password }}';
    CREATE DATABASE {{ .db }} OWNER {{ .user }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .db }} TO {{ .user }};
    {{- end }}