{{- $l1RpcURL := "" }}

{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "l1RpcURL") }}
        {{- $l1RpcURL = index $opSecrets.data "l1RpcURL" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
data:
  API_V2_ENABLED: "true"
  # BACKEND_EXPOSED: "{{ .Values.backend.backendExposed | toString }}"
  BLOCKSCOUT_PROTOCOL: "http"
  BRIDGED_TOKENS_ENABLED: "true"
  CHAIN_ID: "{{ .Values.chainId }}"
  CHAIN_TYPE: "polygon_zkevm"
  COIN: {{ .Values.backend.coin | quote }}
  DATABASE_URL: "postgresql://{{ index $opSecrets.data "dbUser" | b64dec }}:{{ index $opSecrets.data "dbUserPassword" | b64dec }}@{{ index $opSecrets.data "dbHost" | b64dec }}:{{ index $opSecrets.data "dbPort" | b64dec }}/{{ .Values.database.name }}"
  # DB_NAME: "{{ .Values.database.name }}"
  # DB_PASSWORD: "{{ .Values.database.password }}"
  # DB_USER: "{{ .Values.database.user }}"
  DISABLE_INDEXER: "false"
  ECTO_USE_SSL: "false"
  ETHEREUM_JSONRPC_HTTP_INSECURE: "{{ .Values.backend.rpc }}"
  ETHEREUM_JSONRPC_HTTP_URL: "{{ .Values.backend.rpcUrl }}"
  ETHEREUM_JSONRPC_TRACE_URL: "{{ .Values.backend.trace_url }}"
  ETHEREUM_JSONRPC_VARIANT: "geth"
  ETHEREUM_JSONRPC_WS_URL: "{{ .Values.backend.ws_url }}"
  INDEXER_POLYGON_ZKEVM_BATCHES_ENABLED: "true"
  INDEXER_POLYGON_ZKEVM_L1_BRIDGE_CONTRACT: "{{ .Values.backend.bridgeInfo.l1Contract }}"
  INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NETWORK_ID: "{{ .Values.backend.bridgeInfo.l1NetworkId | int }}"
  INDEXER_POLYGON_ZKEVM_L1_BRIDGE_ROLLUP_INDEX: "{{ .Values.backend.bridgeInfo.l1RollupIndex | int }}"
  INDEXER_POLYGON_ZKEVM_L1_BRIDGE_START_BLOCK: "{{ .Values.backend.bridgeInfo.l1StartBlock | int }}"
  INDEXER_POLYGON_ZKEVM_L1_RPC: "{{ $l1RpcURL }}"
  INDEXER_POLYGON_ZKEVM_L2_BRIDGE_CONTRACT: "{{ .Values.backend.bridgeInfo.l2Contract }}"
  INDEXER_POLYGON_ZKEVM_L2_BRIDGE_NETWORK_ID: "{{ .Values.backend.bridgeInfo.l2NetworkId | int }}"
  INDEXER_POLYGON_ZKEVM_L2_BRIDGE_ROLLUP_INDEX: "{{ .Values.backend.bridgeInfo.l2RollupIndex | int }}"
  INDEXER_POLYGON_ZKEVM_L2_BRIDGE_START_BLOCK: "{{ .Values.backend.bridgeInfo.l2StartBlock | int }}"
  LOGO: "/images/blockscout_logo.svg"
  LOGO_FOOTER: "/images/blockscout_logo.svg"
  MIX_ENV: "prod"
  NETWORK: "POE"
  SHOW_OUTDATED_NETWORK_MODAL: "false"
  SUBNETWORK: "{{ .Values.networkName }}"
  SUPPORTED_CHAINS: "[]"
  TITLE: "{{ .Values.networkName }}"
