apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout.componentName" (dict "componentNameKey" "backend" "Values" .Values "Release" .Release "Chart" .Chart) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.blockscout.backend.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blockscout.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "blockscout.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.blockscout.backend.image }}
          ports:
            - containerPort: {{ .Values.blockscout.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          command: ["/bin/sh", "-c"]
          args: ['bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start']
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]
