apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}-backend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-backend.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}-backend
        tags.datadoghq.com/service: blockscout-backend
        tags.datadoghq.com/version: {{ .Values.backend.image }}
        {{- include "blockscout.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - name: app
              containerPort: {{ .Values.backend.ports.app }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
          command: ["/bin/sh", "-c"]
          args: ['bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start']
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]
