apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.blockscout.backend.image }}
          ports:
            - containerPort: {{ .Values.blockscout.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          command: ["/bin/sh", "-c"]
          args: ['bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()" && bin/blockscout start']
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]