apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout.componentName" (dict "componentNameKey" "visualize" "Values" .Values "Release" .Release "Chart" .Chart) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "blockscout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blockscout.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: visualize
          image: {{ .Values.blockscout.visualize.image }}
          ports:
            - containerPort: {{ .Values.blockscout.visualize.port }}
          envFrom:
            - configMapRef:
                name: visualize-config
            - secretRef:
                name: secret-visualize
