{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: "{{ .Values.ingress.hostname }}-secret-tls"
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api/v2
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /api/v1/lines
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-stats
                port:
                  name: app
          - path: /api/v1/counters
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-stats
                port:
                  name: app
          - path: /socket
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /sitemap.xml
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /auth/auth0
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /auth/auth0/callback
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /auth/logout
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  name: app
{{- end }}                