apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "blockscout.fullname" . }}
  labels:
    {{- include "blockscout.labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
{{- if .Values.service.labels }}
{{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: blockscout-http
    protocol: TCP
    port: {{ .Values.service.port | int }}
    targetPort: {{ .Values.service.namedPort | quote}}
  selector:
    {{- include "blockscout.selectorLabels" (dict "context" . "component" .Values.name "name"  .Values.name) | nindent 4 }}