{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-database
    app.kubernetes.io/instance: {{ .Release.Name }}-database
  ports:
    - name: app
      port: {{ .Values.database.ports.app }}
      protocol: TCP
{{- end }}