{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          ports:
            - containerPort: {{ .port }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- if .database.enabled }}
          env:
            - name: DB_HOST
              value: {{ .database.host }}
            - name: DB_PORT
              value: {{ .database.port | quote }}
            - name: DB_NAME
              value: {{ .database.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .database.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .database.secretName }}
                  key: password
          {{- end }}
---
{{- end }}
