{{- range .Values.apps }}
{{- if .tls.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
  namespace: {{ .name }} 
spec:
  parentRefs:
  - kind: Gateway
    name: {{ $.Values.gateway }}
    namespace: {{ $.Values.gateway_namespace }}
  hostnames:
  {{- range .tls.domains }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .name }}-svc
      port: {{ .port }} 
{{- end }}
{{- end }}