{{- range .Values.apps }}
{{- if .tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
  namespace: "gateway"
spec:
  parentRefs:
  - name: {{ $.Values.gateway }}
    sectionName: https
  hostnames:
  {{- range .tls.domains }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .name }}-svc
      port: {{ .port }} 
{{- end }}
{{- end }}