{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: {{ .namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
---
{{- end }}
