apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  bridge-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [SyncDB]
    Database = "postgres"
      [SyncDB.PgStorage]
      User = {{ .Values.config.db.user | quote }}
      Password = {{ .Values.config.db.password | quote }}
      Name = {{ .Values.config.db.name | quote }}
      Host = {{ .Values.config.db.host | quote }}
      Port = {{ .Values.config.db.port | quote }}
      MaxConns = 200

    [Etherman]
    l1URL = {{ .Values.config.etherman.l1Url | quote }}
    L2URLs = [{{ .Values.config.etherman.l2Url | quote }}]

    [Synchronizer]
    SyncInterval = "5s"
    SyncChunkSize = 1000
    ForceL2SyncChunk = {{ .Values.config.synchronizer.forceL2SyncChunk }}

    [BridgeController]
    Store = "postgres"
    Height = 32

    [BridgeServer]
    CacheSize = 100000
    GRPCPort = "9090"
    HTTPPort = "8080"
    DefaultPageLimit = 25
    MaxPageLimit = 100
    BridgeVersion = "v1"
    FinalizedGEREnabled = {{ .Values.config.bridgeServer.finalizedGEREnabled }}

    [BridgeServer.DB]
    Database = "postgres"
      [BridgeServer.DB.PgStorage]
      User = {{ .Values.config.db.user | quote }}
      Password = {{ .Values.config.db.password | quote }}
      Name = {{ .Values.config.db.name | quote }}
      Host = {{ .Values.config.db.host | quote }}
      Port = {{ .Values.config.db.port | quote }}
      MaxConns = 200

    [NetworkConfig]
    L1GenBlockNumber = {{ .Values.config.network.l1GenBlockNumber | int64 }}
    PolygonBridgeAddress = {{ .Values.config.network.polygonBridgeAddress | quote }}
    PolygonZkEVMGlobalExitRootAddress = {{ .Values.config.network.polygonZkEVMGlobalExitRootAddress | quote }}
    PolygonRollupManagerAddress = {{ .Values.config.network.polygonRollupManagerAddress | quote }}
    PolygonZkEVMAddress = {{ .Values.config.network.polygonZkEVMAddress | quote }}
    L2PolygonBridgeAddresses = [{{ .Values.config.network.l2PolygonBridgeAddress | quote }}]
    L2PolygonZkEVMGlobalExitRootAddresses = [{{ .Values.config.network.l2PolygonZkEVMGlobalExitRootAddress | quote }}]
    L2GenBlockNumbers = [{{ .Values.config.network.l2GenBlockNumbers | int64 }}]
    RequireSovereignChainSmcs = [{{ .Values.config.network.requireSovereignChainSmcs }}]

    [ClaimTxManager]
    FrequencyToMonitorTxs = "5s"
    {{ if .Values.config.claimTxManager.privateKey.keyName }}
    PrivateKey = {Method = "GCP", KeyName = {{ .Values.config.claimTxManager.privateKey.keyName | quote }}}
    {{ else }}
    PrivateKey = {Path = "/etc/bridge/keystores/{{ .Values.config.claimTxManager.privateKey.keystoreFileName }}", Password = {{ .Values.config.claimTxManager.privateKey.keystoreFilePassword | quote }}}
    {{ end }}
    Enabled = true
    RetryInterval = "1s"
    AreClaimsBetweenL2sEnabled = {{ .Values.config.claimTxManager.areClaimsBetweenL2sEnabled }}
