apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  config.json: |-
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  bridge-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [SyncDB]
    Database = "postgres"
    User = {{ .Values.config.sensitive.database.user | quote }}
    Password = {{ .Values.config.sensitive.database.password | quote }}
    Name = {{ .Values.config.database.name | quote }}
    Host = {{ .Values.config.database.host | quote }}
    Port = {{ .Values.config.database.port | quote }}

    [Etherman]
    l1URL = {{ .Values.config.sensitive.l1.rpcUrl | quote }}
    L2URLs = [{{ .Values.config.l2.rpcUrl | quote }}]

    [Synchronizer]
    SyncInterval = "5s"
    SyncChunkSize = 1000

    [BridgeController]
    Store = "postgres"
    Height = 32

    [BridgeServer]
    CacheSize = 100000
    GRPCPort = "9090"
    HTTPPort = "8080"
    DefaultPageLimit = 25
    MaxPageLimit = 100
    BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = "postgres"
    User = {{ .Values.config.sensitive.database.user | quote }}
    Password = {{ .Values.config.sensitive.database.password | quote }}
    Name = {{ .Values.config.database.name | quote }}
    Host = {{ .Values.config.database.host | quote }}
    Port = {{ .Values.config.database.port | quote }}

    [NetworkConfig]
    GenBlockNumber = {{ .Values.config.rollupManager.genesisBlockNumber | int64 }}
    PolygonBridgeAddress = {{ .Values.config.rollupManager.bridgeAddress | quote }}
    PolygonZkEVMGlobalExitRootAddress = {{ .Values.config.rollupManager.globalExitRootManagerAddress | quote }}
    PolygonRollupManagerAddress = {{ .Values.config.rollupManager.address | quote }}
    PolygonZkEVMAddress = {{ .Values.config.rollup.address | quote }}
    L2PolygonBridgeAddresses = [{{ .Values.config.rollupManager.bridgeAddress | quote }}]

    [ClaimTxManager]
    FrequencyToMonitorTxs = "5s"
    PrivateKey = {Path = "/etc/bridge/claimtx.keystore", Password = {{ .Values.config.sensitive.wallets.claimtx.password | quote }}}
    Enabled = true
    RetryInterval = "1s"

  claimtx.keystore: |
    {{ .Values.config.wallets.claimtx.keystore }}
