{{- $combinedJson := .Values.combinedJson | fromJson }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  config.json: |-
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  bridge-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [SyncDB]
    Database = {{ .Values.config.db.database | quote }}
    User = {{ .Values.config.db.user | quote }}
    Password = {{ .Values.config.db.password | quote }}
    Name = {{ .Values.config.db.name | quote }}
    Host = {{ .Values.config.db.host | quote }}
    Port = {{ .Values.config.db.port | quote }}

    [Etherman]
    l1URL = {{ .Values.config.etherman.l1Url | quote }}
    L2URLs = [{{ .Values.config.etherman.l2Url | quote }}]

    [Synchronizer]
    SyncInterval = "5s"
    SyncChunkSize = 1000

    [BridgeController]
    Store = "postgres"
    Height = 32

    [BridgeServer]
    CacheSize = 100000
    GRPCPort = "9090"
    HTTPPort = "8080"
    DefaultPageLimit = 25
    MaxPageLimit = 100
    BridgeVersion = "v1"
    [BridgeServer.DB]
    Database = {{ .Values.config.db.database | quote }}
    User = {{ .Values.config.db.user | quote }}
    Password = {{ .Values.config.db.password | quote }}
    Name = {{ .Values.config.db.name | quote }}
    Host = {{ .Values.config.db.host | quote }}
    Port = {{ .Values.config.db.port | quote }}

    [NetworkConfig]
    GenBlockNumber = {{ $combinedJson.deploymentRollupManagerBlockNumber | int64 }}
    PolygonBridgeAddress = {{ $combinedJson.polygonZkEVMBridgeAddress | quote }}
    PolygonZkEVMGlobalExitRootAddress = {{ $combinedJson.polygonZkEVMGlobalExitRootAddress | quote }}
    PolygonRollupManagerAddress = {{ $combinedJson.polygonRollupManagerAddress | quote }}
    PolygonZkEVMAddress = {{ $combinedJson.rollupAddress | quote }}
    L2PolygonBridgeAddresses = [{{ $combinedJson.polygonZkEVMBridgeAddress | quote }}]

    [ClaimTxManager]
    FrequencyToMonitorTxs = "5s"
    PrivateKey = {Path = {{ .Values.config.claimTxManager.path | quote }}, Password = {{ .Values.config.claimTxManager.password | quote }}}
    Enabled = true
    RetryInterval = "1s"

  claimtx.keystore: |
{{ .Values.config.claimTxManager.keystore | indent 4 }}
