{{- $l1RpcURL := "" }}

{{- $claimTxPrivateKeyPassword := "" }}

{{- $bridgeDbName := "" }}
{{- $dbUser := "" }}
{{- $dbUserPassword := "" }}
{{- $dbHost := "" }}
{{- $dbPort := "" }}

{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "claimTxPrivateKeyPassword") }}
        {{- $claimTxPrivateKeyPassword = index $opSecrets.data "claimTxPrivateKeyPassword" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "l1RpcURL") }}
        {{- $l1RpcURL = index $opSecrets.data "l1RpcURL" | b64dec }}
    {{- end }}

    {{- if (index $opSecrets.data "bridgeDbName") }}
        {{- $bridgeDbName = index $opSecrets.data "bridgeDbName" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbUser") }}
        {{- $dbUser = index $opSecrets.data "dbUser" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbUserPassword") }}
        {{- $dbUserPassword = index $opSecrets.data "dbUserPassword" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbHost") }}
        {{- $dbHost = index $opSecrets.data "dbHost" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "dbPort") }}
        {{- $dbPort = index $opSecrets.data "dbPort" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  config.json: |-
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge.fullname" . }}
data:
  bridge-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [SyncDB]
    Database = "postgres"
    User = {{ $dbUser | quote }}
    Password = {{ $dbUserPassword | quote }}
    Name = {{ $bridgeDbName | quote }}
    Host = {{ $dbHost | quote }}
    Port = {{ $dbPort | quote }}
    MaxConns = 200

    [Etherman]
    l1URL = {{ $l1RpcURL | quote }}
    L2URLs = [{{ .Values.config.etherman.l2Url | quote }}]

    [Synchronizer]
    BlockFinality = "FinalizedBlock"
    SyncInterval = "5s"
    SyncChunkSize = 1000

    [BridgeController]
    Store = "postgres"
    Height = 32

    [BridgeServer]
    CacheSize = 100000
    GRPCPort = "9090"
    HTTPPort = "8080"
    DefaultPageLimit = 25
    MaxPageLimit = 100
    BridgeVersion = "v1"
    
    [BridgeServer.DB]
    Database = "postgres"
    User = {{ $dbUser | quote }}
    Password = {{ $dbUserPassword | quote }}
    Name = {{ $bridgeDbName | quote }}
    Host = {{ $dbHost | quote }}
    Port = {{ $dbPort | quote }}
    MaxConns = 200

    [NetworkConfig]
    GenBlockNumber = {{ .Values.config.network.genBlockNumber | int64 }}
    PolygonBridgeAddress = {{ .Values.config.network.polygonBridgeAddress | quote }}
    PolygonZkEVMGlobalExitRootAddress = {{ .Values.config.network.polygonZkEVMGlobalExitRootAddress | quote }}
    PolygonRollupManagerAddress = {{ .Values.config.network.polygonRollupManagerAddress | quote }}
    PolygonZkEVMAddress = {{ .Values.config.network.polygonZkEVMAddress | quote }}
    L2PolygonBridgeAddresses = [{{ .Values.config.network.l2PolygonBridgeAddress | quote }}]
    L2PolygonZkEVMGlobalExitRootAddresses = [{{ .Values.config.network.l2PolygonZkEVMGlobalExitRootAddress | quote }}]
    RequireSovereignChainSmcs = [{{ .Values.config.network.requireSovereignChainSmcs }}]

    [ClaimTxManager]
    FrequencyToMonitorTxs = "5s"
    PrivateKey = {Path = {{ .Values.config.claimTxManager.path | quote }}, Password = {{ $claimTxPrivateKeyPassword | quote }}}
    Enabled = true
    RetryInterval = "1s"
