apiVersion: v1
kind: Service
metadata:
  name: {{ include "bridge.fullname" . }}
  labels:
    {{- include "bridge.labels" . | nindent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": \"{{ include "bridge.fullname" . }}-healthcheck\"}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bridge.selectorLabels" . | nindent 4 }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "bridge.fullname" . }}-healthcheck
spec:
  healthCheck:
    timeoutSec: 1
    type: HTTP
    requestPath: /
    port: {{ .Values.service.port }}
