# TODO: The GCP service account used here should be correctly configured from
# the terraform module with the equivalent of the following:
#
# 1. Give permission to the GCP service account to download files from GCP buckets:
# gcloud projects add-iam-policy-binding [PROJECT_ID] \
#   --member="serviceAccount:[SERVICE_ACCOUNT_EMAIL]" \
#   --role="roles/storage.objectViewer"
#
# 2. Allow the k8s service account to impersonate the GCP service account:
# gcloud iam service-accounts add-iam-policy-binding [GCP_SA_EMAIL] \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:[PROJECT_ID].svc.id.goog[[NAMESPACE]/[KSA_NAME]]"
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "op-geth.serviceAccountName" . }}
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
