apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zkevm-prover.fullname" . }}-config
  labels:
    {{- include "zkevm-prover.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "runExecutorServer": false,
      "runExecutorClient": false,
      "runExecutorClientMultithread": false,
      "runStateDBServer": false,
      "runStateDBTest": false,
      "runAggregatorServer": false,
      "runAggregatorClient": {{ ternary "false" "true" .Values.isMockProver | quote }},
      "runAggregatorClientMock": {{ ternary "true" "false" .Values.isMockProver | quote }},
      "proverName": "zkevm-prover",
      "runFileGenBatchProof": false,
      "runFileGenAggregatedProof": false,
      "runFileGenFinalProof": false,
      "runFileProcessBatch": false,
      "runFileProcessBatchMultithread": false,
      "runFileExecutor": false,
      "runKeccakScriptGenerator": false,
      "runKeccakTest": false,
      "runStorageSMTest": false,
      "runBinarySMTest": false,
      "runMemAlignSMTest": false,
      "runSHA256Test": false,
      "runBlakeTest": false,
      "executeInParallel": true,
      "useMainExecGenerated": false,
      "useProcessBatchCache": true,
      "saveRequestToFile": false,
      "saveInputToFile": true,
      "saveDbReadsToFile": true,
      "saveDbReadsToFileOnChange": false,
      "saveOutputToFile": true,
      "saveFilesInSubfolders": false,
      "saveProofToFile": true,
      "saveResponseToFile": false,
      "loadDBToMemCache": false,
      "loadDBToMemCacheInParallel": false,
      "dbMTCacheSize": 16384,
      "dbProgramCacheSize": 16384,
      "dbMultiWrite": true,
      "dbFlushInParallel": false,
      "opcodeTracer": false,
      "logRemoteDbReads": false,
      "logExecutorServerResponses": false,
      "executorServerPort": 50071,
      "executorROMLineTraces": false,
      "executorClientPort": 50071,
      "executorClientHost": "127.0.0.1",
      "stateDBServerPort": 50061,
      "stateDBURL": "local",
      "aggregatorServerPort": 50081,
      "aggregatorClientPort": {{ .Values.aggregator.port }},
      "aggregatorClientHost": "{{ .Values.aggregator.host }}",
      "aggregatorClientMockTimeout": 10000000,
      "aggregatorClientWatchdogTimeout": 3600000000,
      "mapConstPolsFile": false,
      "mapConstantsTreeFile": false,
      "inputFile": "testvectors/aggregatedProof/recursive1.zkin.proof_0.json",
      "inputFile2": "testvectors/aggregatedProof/recursive1.zkin.proof_1.json",
      "outputPath": "output",
      "configPath": "/mnt/prover/config",
      "zkevmCmPols_disabled": "/mnt/prover/runtime/zkevm.commit",
      "c12aCmPols": "runtime/c12a.commit",
      "recursive1CmPols_disabled": "runtime/recursive1.commit",
      "recursive2CmPols_disabled": "runtime/recursive2.commit",
      "recursivefCmPols_disabled": "runtime/recursivef.commit",
      "finalCmPols_disabled": "runtime/final.commit",
      "publicsOutput": "public.json",
      "proofFile": "proof.json",
      "databaseURL": "local",
      "hashDBSingleton": false,
      "dbNodesTableName": "state.nodes",
      "dbProgramTableName": "state.program",
      "dbConnectionsPool": true,
      "cleanerPollingPeriod": 600,
      "requestsPersistence": 3600,
      "maxExecutorThreads": 20,
      "maxProverThreads": 8,
      "maxStateDBThreads": 8,
      "jsonLogs": true,
      "stateManager": false
    }
