---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zkevm-prover-deployment
  labels:
  {{- include "zkevm-prover.labels" $ | nindent 4 }}
  {{- toYaml .Values.podLabels | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "zkevm-prover.selectorLabels" $ | nindent 6 }}
    {{- toYaml .Values.podLabels | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "zkevm-prover.labels" $ | nindent 8 }}
      {{- toYaml .Values.podLabels | nindent 8 }}
      annotations:
        ad.datadoghq.com/zkevm-prover.logs: '[{"source": "zkevm-prover"}]'
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: zkevm-prover-sa
      containers:
      - name: zkevm-prover
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: {{ ternary "1" "222" .Values.isMockProver | quote }}
            memory: {{ ternary "6Gi" "850Gi" .Values.isMockProver | quote }}
        command:
        - /bin/sh
        - -c
        - "zkProver -c /etc/zkevm-prover/config.json"
        volumeMounts:
        - name: zkevm-prover-config
          mountPath: /etc/zkevm-prover
          readOnly: true
        - name: prover-fs-gcs
          mountPath: /mnt/prover
          readOnly: true
      volumes:
      - name: zkevm-prover-config
        configMap:
          name: zkevm-prover-config
          items:
          - key: config.json
            path: config.json
      - name: prover-fs-gcs
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: {{ .Values.gcs.bucket }}
            mountOptions: "implicit-dirs,only-dir={{ .Values.gcs.version }}"
      {{ if not .Values.isMockProver }}
      nodeSelector:
        cloud.google.com/compute-class: Performance
        cloud.google.com/machine-family: n2d
        cloud.google.com/gke-spot: "true"
      {{ end }}
