piVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pool-manager.fullname" . }}
data:
  config.json: |-
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pool-manager.fullname" . }}
data:
  pool-manager-config.toml: |
    [Log]
    Environment = {{ .Values.config.log.environment | quote }}
    Level = {{ .Values.config.log.level | quote }}
    Outputs = ["stderr"]

    [Server]
    Host = "0.0.0.0"
    Port = {{ .Values.config.server.port }}
    ReadTimeout = "60s"
    WriteTimeout = "60s"
    MaxRequestsPerIPAndSecond = 500
    EnableHttpLog = true
    BatchRequestsEnabled = false
    BatchRequestsLimit = 20

    [DB]
    User = {{ .Values.config.db.user | quote }}
    Password = {{ .Values.config.db.password | quote }}
    Name = {{ .Values.config.db.name | quote }}
    Host = {{ .Values.config.db.host | quote }}
    Port = {{ .Values.config.db.port | quote }}
    EnableLog = false
    MaxConns = 200

    [Sender]
    SequencerURL = {{ .Values.config.sender.sequencerURL | quote }}
    ResendTxsCheckInterval = "1s"
    Workers = 5
    QueueSize = 25

    [Monitor]
    L2NodeURL = {{ .Values.config.monitor.l2NodeURL | quote }}
    Workers = 5
    QueueSize = 25
    RetryWaitInterval = "3s"
    InitialWaitInterval = "1s"
    TxLifeTimeMax = "300s"

