apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pool-manager.fullname" . }}
  labels:
    {{- include "pool-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pool-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pool-manager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pool-manager.serviceAccountName" . }}
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      {{- if or .Values.envSubstitution.enabled .Values.initContainers }}
      initContainers:
        {{- if .Values.envSubstitution.enabled }}
        - name: config-env-substitution
          image: alpine:latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              apk add gettext > /dev/null 2>&1
              envsubst < /config-raw/config.toml > /config/config.toml
          envFrom:
            {{- range $name, $_ := $.Values.onePasswordSecrets }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          volumeMounts:
            - name: config-raw
              mountPath: /config-raw
              readOnly: true
            - name: config
              mountPath: /config
        {{- end }}
        {{- with .Values.initContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "pool-manager.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{- range .Values.image.command }}
            - {{ . }} {{- end}}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{- range .Values.image.args }}
            - {{ . }} {{- end}}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/pool-manager/
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
      volumes:
        - name: {{ ternary "config" "config-raw" .Values.envSubstitution.enabled }}
          configMap:
            name: {{ include "pool-manager.fullname" . }}
            items:
              - key: "config.toml"
                path: "config.toml"
        {{- if .Values.envSubstitution.enabled }}
        - name: config
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
