{{- if .Values.gatewayAPI.enabled }}
{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "agglayer.name" . }}-grpc-healthcheck
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-grpc
  default:
    checkIntervalSec: {{ .Values.gatewayAPI.healthCheck.grpc.checkIntervalSec }}
    timeoutSec: {{ .Values.gatewayAPI.healthCheck.grpc.timeoutSec }}
    healthyThreshold: {{ .Values.gatewayAPI.healthCheck.grpc.healthyThreshold }}
    unhealthyThreshold: {{ .Values.gatewayAPI.healthCheck.grpc.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.ports.readrpc }}
        requestPath: /health
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "agglayer.name" . }}-app-healthcheck
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-app
  default:
    checkIntervalSec: {{ .Values.gatewayAPI.healthCheck.app.checkIntervalSec }}
    timeoutSec: {{ .Values.gatewayAPI.healthCheck.app.timeoutSec }}
    healthyThreshold: {{ .Values.gatewayAPI.healthCheck.app.healthyThreshold }}
    unhealthyThreshold: {{ .Values.gatewayAPI.healthCheck.app.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.ports.readrpc }}
        requestPath: /health
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "agglayer.name" . }}-admin-healthcheck
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-admin
  default:
    checkIntervalSec: {{ .Values.gatewayAPI.healthCheck.admin.checkIntervalSec }}
    timeoutSec: {{ .Values.gatewayAPI.healthCheck.admin.timeoutSec }}
    healthyThreshold: {{ .Values.gatewayAPI.healthCheck.admin.healthyThreshold }}
    unhealthyThreshold: {{ .Values.gatewayAPI.healthCheck.admin.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.ports.readrpc }}
        requestPath: /health
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "agglayer.name" . }}-admin-iap-policy
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-admin
  default:
    timeoutSec: {{ .Values.gatewayAPI.backendPolicy.admin.timeoutSec }}
    iap:
      enabled: true
      clientID: {{ index $opSecrets.data "admin_api_oauth_client_id" | b64dec }}
      oauth2ClientSecret:
        name: {{ include "agglayer.name" . }}-admin-oauth-gateway
    {{- if .Values.gatewayAPI.securityPolicy }}
    securityPolicy: {{ .Values.gatewayAPI.securityPolicy }}
    {{- end }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "agglayer.name" . }}-grpc-policy
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-grpc
  default:
    timeoutSec: {{ .Values.gatewayAPI.backendPolicy.grpc.timeoutSec }}
    {{- if .Values.gatewayAPI.securityPolicy }}
    securityPolicy: {{ .Values.gatewayAPI.securityPolicy }}
    {{- end }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "agglayer.name" . }}-app-policy
  namespace: {{ .Release.Namespace }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ include "agglayer.fullname" . }}-app
  default:
    timeoutSec: {{ .Values.gatewayAPI.backendPolicy.app.timeoutSec }}
    {{- if .Values.gatewayAPI.securityPolicy }}
    securityPolicy: {{ .Values.gatewayAPI.securityPolicy }}
    {{- end }}
{{- end }}
