{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agglayer.name" . }}-admin-oauth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client_id: {{ index $opSecrets.data "admin_api_oauth_client_id" | b64dec }}
  client_secret: {{ index $opSecrets.data "admin_api_oauth_client_secret" | b64dec }}