{{- $networkPrivateKey := "" }}
{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace "op-secrets") }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "NETWORK_PRIVATE_KEY") }}
        {{- $networkPrivateKey = index $opSecrets.data "NETWORK_PRIVATE_KEY" | b64dec }}
    {{- end }}
{{- end }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "agglayer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agglayer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agglayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # https://cloud.google.com/kubernetes-engine/docs/how-to/extended-duration-pods
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        # https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: {{ .Values.gcsfuse.sidecar.ephemeralStorageLimit | quote }}
        # tuning
        gke-gcsfuse/cpu-limit: {{ .Values.gcsfuse.sidecar.cpuLimit | quote }}
        gke-gcsfuse/memory-limit: {{ .Values.gcsfuse.sidecar.memoryLimit | quote }}
        gke-gcsfuse/metadata-prefetch-cpu-request: {{ .Values.gcsfuse.metadataPrefetch.cpuRequest | quote }}
        gke-gcsfuse/metadata-prefetch-cpu-limit: {{ .Values.gcsfuse.metadataPrefetch.cpuLimit | quote }}
        gke-gcsfuse/metadata-prefetch-memory-request: {{ .Values.gcsfuse.metadataPrefetch.memoryRequest | quote }}
        gke-gcsfuse/metadata-prefetch-memory-limit: {{ .Values.gcsfuse.metadataPrefetch.memoryLimit | quote }}

        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ports.telemetry | quote }}
      labels:
        {{- include "agglayer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agglayer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - agglayer
            - run
          args:
            - "--cfg"
            - "/etc/agglayer/config.toml"
          ports:
            - containerPort: {{ .Values.ports.grpc }}
            - containerPort: {{ .Values.ports.readrpc }}
            - containerPort: {{ .Values.ports.admin }}
            - containerPort: {{ .Values.ports.telemetry }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.readrpc }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.readrpc }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: "/etc/agglayer"
              name: config
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
            - name: backup
              mountPath: {{ .Values.backup.path | quote }}
              readOnly: false
          env:
            - name: NETWORK_PRIVATE_KEY
              value: {{ $networkPrivateKey }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.dshm.sizeLimit }}
        - name: config
          configMap:
            name: agglayer-config
            items:
              - key: "config.toml"
                path: "config.toml"
        - name: backup
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: {{ .Values.backup.bucket | quote }}
              mountOptions: "implicit-dirs,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1,metadata-cache:ttl-secs:-1,metadata-cache:negative-ttl-secs:0,file-system:kernel-list-cache-ttl-secs:-1,gcs-connection:max-conns-per-host:100"
              gcsfuseMetadataPrefetchOnMount: "true"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ include "agglayer.fullname" . }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
