apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "agglayer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agglayer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agglayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        ad.datadoghq.com/{{ .Chart.Name }}.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:2223/metrics",
                  "metrics": [
                    {"execute": "agglayer.execute"},
                    {"check_tx": "agglayer.check_tx"},
                    {"send_tx": "agglayer.send_tx"},
                    {"settle": "agglayer.settle"},
                    {"target_info": "agglayer.target_info"},
                    {"verify_signature": "agglayer.verify_signature"},
                    {"verify_zkp": "agglayer.verify_zkp"}
                  ]
                }
              ]
            }
          }
      labels:
        {{- include "agglayer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agglayer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - agglayer
            - run
          args:
            - "--cfg"
            - "/etc/agglayer/config.toml"
          ports:
            - containerPort: {{ .Values.ports.app }}
            - containerPort: {{ .Values.ports.telemetry }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.app }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.app }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/agglayer"
              name: config
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
      volumes:
        - name: config
          configMap:
            name: agglayer-config
            items:
              - key: "config.toml"
                path: "config.toml"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ include "agglayer.fullname" . }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}