---
mountRawConfig: false

onePasswordItems:
  aggkit-bridge-katana: "vaults/infra-common-production-cluster/items/aggkit-bridge-katana"

env: production

metadata:
  service: aggkit-bridge-katana

nodeSelector:
  cloud.google.com/compute-class: general-amd64

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "amd64"
    effect: "NoSchedule"

podLabels: {}

container:
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/agglayer/aggkit
    tag: 0.7.0-beta12

  extraVolumeMounts:
    - name: config
      mountPath: "/etc/aggkit"

service:
  type: ClusterIP

storage:
  storageClass: "balanced-ha-storage"
  path: /data
  size: 500Gi

extraVolumes:
  - name: config
    emptyDir: {}

  - name: config-raw
    configMap:
      name: aggkit-bridge-katana
      items:
        - key: config.toml
          path: config.toml

initContainers:
  - name: config-env-substitution
    image: alpine:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "(apk add gettext &> /dev/null) && (envsubst < /config-raw/config.toml > /config/config.toml)"
    volumeMounts:
      - mountPath: "/config-raw"
        name: config-raw
        readOnly: true
      - mountPath: "/config"
        name: config
    envFrom:
      - secretRef:
          name: aggkit-bridge-katana

config:
  bridgeAddress: "0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe"
  components:
    - bridge

  l1:
    chainId: 1
    globalExitRootAddress: "0x580bda1e7a0cfae92fa7f6c20a3794f169ce3cfb"
    polTokenAddress: "0x455e53cbb86018ac2b8092fdcd39d8444affc3f6"
    rollupAddress: "0x100d3ca4f97776a40a7d93db4abf0fea34230666"
    rollupBlockNumber: 22431675
    rollupManagerAddress: "0x5132a183e9f3cb7c848b0aac5ae0c4f0491b7ab2"
    rollupManagerBlockNumber: 19218658
    syncBlockChunkSize: 1000
    rpcUrl: "$L1_RPC_URL"

  l2:
    agglayerAddress: "0x20A53dCb196cD2bcc14Ece01F358f1C849aA51dE"
    bridgeAddress: "0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe"
    chainId: 747474
    globalExitRootAddress: "0xa40d5f56745a118d0906a34e69aec8c0db1cb8fa"
    rollupId: 20
    rpcURL: https://rpc.katanarpc.com

  log:
    environment: production # "production" or "development"
    level: info
