---
metadata:
  env: bali
  costCenter: agglayer
  service: aggkit

onePasswordSecrets:
  # aggkit: "vaults/myvault/items/myitem"

# Enable to replace $ENV_VARS in the configmap from a Kubernetes secret
  # Secret names are derived from onePasswordSecrets keys
envSubstitution:
  enabled: true

# Pod annotations (e.g. ad.datadoghq.com/tags for Datadog)
podAnnotations: {}
# podAnnotations:
#   ad.datadoghq.com/tags: '{"role": "aggsender", "network": "mynetwork"}'

nodeSelector: {}

tolerations: []

initContainers: []

extraVolumes: []

topologySpreadConstraints: []

replicas: 1

container:
  extraVolumeMounts: []

  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/agglayer/aggkit
    tag: latest

  ports:
    aggsender: 5576
    bridge: 5577
    validator: 5578 # named validator as is common to aggsender and aggsender-validator
    prometheus: 9091

service:
  type: ClusterIP
  clusterIP: None

ingresses:
  aggsender:
    create: false
    hostname: "something.dev.polygon"
  bridge:
    create: false
    hostname: "something-else.dev.polygon"
  aggsenderValidator:
    create: false
    hostname: "something-else-else.dev.polygon"

httpRoutes:
  aggsender:
    create: false
    hostname: domain.example
    gateway:
      name: gateway
      namespace: gateways
  bridge:
    create: false
    hostname: domain.example
    gateway:
      name: gateway
      namespace: gateways
  aggsenderValidator:
    create: false
    hostname: domain.example
    gateway:
      name: gateway
      namespace: gateways

serviceAccount:
  create: false
  annotations: {}

storage:
  path: /data
  size: 500Gi

podSecurityContext: {}
securityContext: {}

config:
  # list of components: aggsender, aggsender-validator, aggoracle, bridge
  components:
    - aggsender
    - aggoracle

  aggsender:
    certificateSendInterval: 1m
    checkSettledInterval: 5s
    checkStatusCertificateInterval: 1m
    dryRun: false
    maxCertSize: 8388608
    maxL2BlockNumber: 0
    unsetClaimsMaxLogBlockRange: 0
    mode: "PessimisticProof" # PessimisticProof (PP) or AggchainProof (FEP)
    retryCertAfterInError: true
    saveCertificatesToFilesPath: /tmp

    # Set this if aggsender.mode is AggchainProof
    # aggkitProverClient:
    #   url: "http://aggkit-prover:4446"
    #   useTLS: true

    agglayerClient:
      url: "http://agglayer:4444"
      useTLS: true

    validatorClient:
      url: "http://localhost:5578"
      useTLS: false

    privateKey:
      keyName: "" # if this string is not empty, aggsender will try to use KMS
      keystoreFileName: "aggsender.keystore"
      keystoreFilePassword: "aggsenderKeystorePassword"

    optimisticModeEnabled: false

  aggsenderValidator:
    mode: "PessimisticProof" # PessimisticProof (PP) or AggchainProof (FEP)

    agglayerClient:
      url: "http://agglayer:4444"
      useTLS: true

    privateKey:
      keyName: "" # if this string is not empty, aggsender-validator will try to use KMS
      keystoreFileName: "aggsenderValidator.keystore"
      keystoreFilePassword: "aggsenderValidatorKeystorePassword"

  aggoracle:
    enableAggoracleCommittee: false
    aggoracleCommitteeAddr: "0x"

    privateKey:
      keyName: "" # if this string is not empty, aggoracle will try to use KMS
      keystoreFileName: "aggoracle.keystore"
      keystoreFilePassword: "aggoracleKeystorePassword"

  l1InfoTreeSync:
    blockFinality: "FinalizedBlock" # "LatestBlock/-6" for fast L1 deposits

  reorgDetectorL1:
    blockFinality: "FinalizedBlock"

  bridgeL1Sync:
    blockFinality: "LatestBlock" # "LatestBlock/-6" for fast L1 deposits
    initialBlockNum: 0
    syncBlockChunkSize: 100

  reorgDetectorL2:
    blockFinality: "LatestBlock"

  bridgeL2Sync:
    blockFinality: "LatestBlock"
    syncBlockChunkSize: 100

  l2GERSync:
    blockFinality: "LatestBlock"
    syncBlockChunkSize: 100

  l1:
    bridgeAddress: "0x123"
    chainId: 123
    globalExitRootAddress: "0x123"
    polTokenAddress: "0x123"
    rollupAddress: "0x123"
    rollupBlockNumber: 123
    rollupManagerAddress: "0x123"
    rollupManagerBlockNumber: 123
    RPCURL: http://example.com
    syncBlockChunkSize: 1000

  l2:
    agglayerAddress: "0x123"
    bridgeAddress: "0x123"
    chainId: 123
    globalExitRootAddress: "0x123"
    RPCURL: http://localhost:8545
    initialBlockNum: 0

  log:
    environment: development # "production" or "development"
    level: info

  prometheus:
    enabled: true
    host: 0.0.0.0

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 1
    memory: 4Gi
