apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: web-apps-gateway 
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    networking.gke.io/certmap: {{ .Values.gateway.certmap }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}  
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces: 
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
  