apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdk-erigon.fullname" . }}
data:
  dynamic-integration-allocs.json: |-
{{ .Values.dynamicIntegrationAllocs | indent 4 }}
  dynamic-integration-chainspec.json: |-
{{ .Values.dynamicIntegrationChainspec | indent 4 }}
  dynamic-integration-conf.json: |-
{{ .Values.dynamicIntegrationConf | indent 4 }}
  first-batch-conf.json: |-
{{ .Values.firstBatchConf | indent 4 }}
