{{- if .Values.httpRoutes.rpc.create -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "cdk-erigon.fullname" . }}
  labels:
    {{- include "cdk-erigon.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.readinessProbe.periodSeconds }}
    timeoutSec: {{ .Values.readinessProbe.timeoutSeconds }}
    healthyThreshold: {{ .Values.readinessProbe.successThreshold }}
    unhealthyThreshold: {{ .Values.readinessProbe.failureThreshold }}
    config:
      type: TCP # Erigon's /health expects POST with JSON body {} (see livenessProbe/readinessProbe in statefulset).
      tcpHealthCheck:
        port: {{ .Values.service.rpc.port }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "cdk-erigon.fullname" . }}
{{- end }}
