{{- if .Values.ingress.rpc.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cdk-erigon.fullname" . }}-rpc
  labels:
    {{- include "cdk-erigon.labels" . | nindent 4 }}
  {{- with .Values.ingress.rpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.rpc.hostname }}
      secretName: "{{ .Values.ingress.rpc.hostname }}-secret-tls"
  rules:
    - host: {{ .Values.ingress.rpc.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cdk-erigon.fullname" . }}
                port:
                  name: rpc
{{- end }}
