apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cdk-erigon.fullname" . }}
  labels:
    {{- include "cdk-erigon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "cdk-erigon.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "cdk-erigon.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cdk-erigon.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cdk-erigon.serviceAccountName" . }}
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.envSubstitution.enabled .Values.initContainers }}
      initContainers:
        {{- if .Values.envSubstitution.enabled }}
        - name: config-env-substitution
          image: alpine:latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              apk add gettext > /dev/null 2>&1
              envsubst < /config-raw/erigon.yaml > /config/erigon.yaml
              cp /config-raw/dynamic-{{ .Values.config.l2.networkName }}-allocs.json /config/
              cp /config-raw/dynamic-{{ .Values.config.l2.networkName }}-chainspec.json /config/
              cp /config-raw/dynamic-{{ .Values.config.l2.networkName }}-conf.json /config/
              cp /config-raw/first-batch-conf.json /config/
          envFrom:
            {{- range $name, $_ := $.Values.onePasswordSecrets }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          volumeMounts:
            - name: config-raw
              mountPath: /config-raw
              readOnly: true
            - name: config
              mountPath: /config
        {{- end }}
        {{- with .Values.initContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "cdk-erigon.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CDK_ERIGON_SEQUENCER
              value: {{ ternary 1 0 .Values.config.isSequencer | quote }}
          {{ if .Values.image.command }}
          command: {{- range .Values.image.command }}
            - {{ . }} {{- end}}
          {{- end}}
          {{ if .Values.image.args }}
          args: {{- range .Values.image.args }}
            - {{ . }} {{- end}}
          {{- end}}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpc.port }}
              protocol: TCP
            - name: datastream
              containerPort: {{ .Values.service.datastream.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storage.path }}
              readOnly: false
            - name: config
              mountPath: /etc/cdk-erigon/
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ ternary "config-raw" "config" .Values.envSubstitution.enabled }}
          configMap:
            name: {{ include "cdk-erigon.fullname" . }}
            items:
              - key: "dynamic-integration-allocs.json"
                path: "dynamic-{{ .Values.config.l2.networkName }}-allocs.json"
              - key: "dynamic-integration-chainspec.json"
                path: "dynamic-{{ .Values.config.l2.networkName }}-chainspec.json"
              - key: "dynamic-integration-conf.json"
                path: "dynamic-{{ .Values.config.l2.networkName }}-conf.json"
              - key: "erigon.yaml"
                path: "erigon.yaml"
              - key: "first-batch-conf.json"
                path: "first-batch-conf.json"
        {{- if .Values.envSubstitution.enabled }}
        - name: config
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- with .Values.storage.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
