{{- range .Values.frontend.apps }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway

metadata:
  name: {{ .name }}-gateway
  namespace: {{ $.Values.frontend.namespace }}
  annotations:
    networking.gke.io/certmap: {{ .certmap }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
---
{{- end }}