{{- range .Values.frontend.apps }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
  namespace: {{ $.Values.frontend.namespace }}
spec:
  parentRefs:
  - name: {{ .name }}-gateway
    sectionName: https  # Routes HTTPS traffic
  hostnames:
  {{- range .tls.domains }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .name }}-svc
      port: {{ .port }}
      
# HTTP to HTTPS redirect, todo: verify if this is needed
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: {{ .name }}-redirect
# spec:
#   parentRefs:
#   - name: {{ .name }}-gateway
#     sectionName: http
#   hostnames:
#   {{- range .tls.domains }}
#   - {{ . | quote }}
#   {{- end }}
#   rules:
#   - filters:
#     - type: RequestRedirect
#       requestRedirect:
#         scheme: https
#         statusCode: 301
# ---
{{- end }}