apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "op-node.fullname" . }}
  selector:
    matchLabels:
      {{- include "op-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "op-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "op-node.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "op-node.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              op-node \
                --l2={{ .Values.config.l2.opRethAuthUrl }} \
                --l2.jwt-secret=/chainconfig/jwt.txt \
                --sequencer.enabled={{ .Values.config.sequencer.enabled }} \
                --p2p.no-discovery=true \
                --p2p.disable={{ not .Values.service.p2p.enabled }} \
                {{- if .Values.service.p2p.enabled }}
                --p2p.listen.tcp={{ .Values.service.p2p.port }} \
                {{- end }}
                {{- if .Values.config.sequencer.enabled }}
                --sequencer.l1-confs={{ .Values.config.sequencer.l1Confs }} \
                --p2p.sequencer.key="${AGGSENDER_PRIVATE_KEY}" \
                {{- end }}
                --verifier.l1-confs={{ .Values.config.verifier.l1Confs }} \
                {{- if and (not .Values.config.sequencer.enabled) .Values.config.verifier.sequencerHttp }}
                --rollup.sequencer-http={{ .Values.config.verifier.sequencerHttp }} \
                {{- end }}
                --rollup.config=/chainconfig/rollup.json \
                --rpc.addr=0.0.0.0 \
                --rpc.enable-admin \
                --l1="${L1_RPC_URL}" \
                --l1.beacon="${L1_RPC_URL}" \
                --log.level={{ .Values.config.log.level }} \
                --log.format={{ .Values.config.log.format }} \
                {{- range .Values.config.extraOptions }}
                --{{ . }} \
                {{- end }}
                --safedb.path=/data
          {{- if .Values.onePasswordSecrets }}
          envFrom:
            {{- range $name, $_ := .Values.onePasswordSecrets }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          {{- end }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpc.port }}
              protocol: TCP
            {{- if .Values.service.p2p.enabled }}
            - name: p2p
              containerPort: {{ .Values.service.p2p.port }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/chainconfig"
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ include "op-node.fullname" . }}
                  items:
                    - key: "rollup.json"
                      path: "rollup.json"
              {{- range $name, $_ := .Values.onePasswordSecrets }}
              - secret:
                  name: {{ $name }}
                  items:
                    - key: "jwt"
                      path: "jwt.txt"
              {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- with .Values.storage.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
