apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "op-node.fullname" . }}
  selector:
    matchLabels:
      {{- include "op-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "op-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "op-node.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-rollup
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag  }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command:
          - gcloud
          args:
          - storage
          - cp
          - {{ .Values.config.bucket | quote }}
          - {{ .Values.config.path }}
          volumeMounts:
            - mountPath: {{ .Values.config.path | quote }}
              name: config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - op-node
          args:
            - --p2p.disable=false
            - --p2p.netrestrict=240.8.0.0/14
            - --p2p.no-discovery=true
            - --p2p.priv.path={{ .Values.storage.path }}/opnode_p2p_priv.txt
            - --l2=http://{{ .Values.config.l2.opGethReleaseName }}-$(INDEX).{{ .Values.config.l2.opGethReleaseName }}.{{ .Release.Namespace }}:8551
            - --l2.jwt-secret={{ .Values.config.path }}/jwt.txt
            - --sequencer.l1-confs=5
            - --verifier.l1-confs=4
            - --rpc.addr=0.0.0.0
            - --rpc.enable-admin
            {{ if .Values.config.key.useKms }}
            - --signer.tls.enabled=false
            - --signer.endpoint=http://localhost:2222
            - --signer.address={{ .Values.config.key.address }}
            {{ else }}
            {{ end }}
            {{ if .Values.sequencer }}
            - --sequencer.enabled
            {{ end }}
            - --l1={{ .Values.config.l1.rpc }}
            - --l1.beacon={{ .Values.config.l1.beacon }}
            - --rollup.config={{ .Values.config.path }}/rollup.json
            {{- range .Values.config.extraOptions }}
            - --{{ . }}
            {{- end}}
            - --metrics.enabled={{ .Values.config.metrics }}
            - --metrics.port={{ .Values.service.metrics.port }}
            - --metrics.addr=0.0.0.0
            - --safedb.path={{ .Values.storage.path }}
            - --syncmode={{ .Values.config.syncMode }}
          env:
          - name: INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpc.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.config.path | quote }}
              name: config
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
        {{ if .Values.config.key.useKms }}
        - name: {{ .Chart.Name }}-op-signer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: ghcr.io/tnobayashi/infra/op-signer:op-signer-v0.0.2
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          args:
            - --tls.enabled=false
            - --config=/etc/op-signer/config.yaml
            - --rpc.port=2222
          volumeMounts:
            - name: op-signer
              mountPath: "/etc/op-signer/"
              readOnly: true
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        {{ if .Values.config.key.useKms }}
        - name: op-signer
          projected:
            sources:
              - configMap:
                  name: {{ include "op-node.fullname" . }}-op-signer
                  items:
                    - key: "config.yaml"
                      path: "config.yaml"
        {{ end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.storage.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
