apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aggkit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "aggkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aggkit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "aggkit.serviceAccountName" . }}
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "aggkit.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      {{- if or .Values.envSubstitution.enabled .Values.initContainers }}
      initContainers:
        {{- if .Values.envSubstitution.enabled }}
        - name: config-env-substitution
          image: alpine:latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              apk add gettext > /dev/null 2>&1
              envsubst < /config-raw/config.toml > /config/config.toml
          envFrom:
            {{- range $name, $_ := $.Values.onePasswordSecrets }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          volumeMounts:
            - name: config-raw
              mountPath: /config-raw
              readOnly: true
            - name: config
              mountPath: /config
        {{- end }}
        {{- with .Values.initContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - aggkit
          args:
            - run
            - --cfg=/etc/aggkit/config/config.toml
            - --components={{ .Values.config.components | join "," }}
          ports:
            - name: aggsender
              containerPort: {{ .Values.container.ports.aggsender }}
              protocol: TCP
            - name: bridge
              containerPort: {{ .Values.container.ports.bridge }}
              protocol: TCP
            - name: validator
              containerPort: {{ .Values.container.ports.validator }}
              protocol: TCP
            {{- if .Values.config.prometheus.enabled }}
            - name: prometheus
              containerPort: {{ .Values.container.ports.prometheus }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.container.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            - mountPath: "/etc/aggkit/config"
              name: config
              readOnly: true
            - mountPath: "/etc/aggkit/keystores"
              name: keystores
              readOnly: true
            - mountPath: {{ .Values.storage.path | quote }}
              name: data
      volumes:
        - name: {{ ternary "config-raw" "config" .Values.envSubstitution.enabled }}
          configMap:
            name: {{ include "aggkit.fullname" . }}
            items:
              - key: "config.toml"
                path: "config.toml"
        {{- if .Values.envSubstitution.enabled }}
        - name: config
          emptyDir: {}
        {{- end }}
        - name: keystores
          secret:
            name: aggkit # Must match the name of the secret in the .Values.onePasswordSecrets list
            items:
              {{- if and (has "aggsender" .Values.config.components) (eq .Values.config.aggsender.privateKey.keyName "") }}
              - key: {{ .Values.config.aggsender.privateKey.keystoreFileName }}
                path: {{ .Values.config.aggsender.privateKey.keystoreFileName }}
              {{- end }}
              {{- if and (has "aggsender-validator" .Values.config.components) (eq .Values.config.aggsenderValidator.privateKey.keyName "") }}
              - key: {{ .Values.config.aggsenderValidator.privateKey.keystoreFileName }}
                path: {{ .Values.config.aggsenderValidator.privateKey.keystoreFileName }}
              {{- end }}
              {{- if and (has "aggoracle" .Values.config.components) (eq .Values.config.aggoracle.privateKey.keyName "") }}
              - key: {{ .Values.config.aggoracle.privateKey.keystoreFileName }}
                path: {{ .Values.config.aggoracle.privateKey.keystoreFileName }}
              {{- end }}
        {{- with .Values.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- with .Values.storage.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
