gateway: web-apps-gateway
gateway_namespace: gateway
apps:
  - name: first
    replicaCount: 2
    certmap: "cert-map-prj-polygonlabs-webapps-dev"
    image:
      repository: nginx
      tag: latest
    port: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    database: {}
    tls:
      enabled: true
      domains:
        - "test-static-webapp.polygon.technology"

  - name: second
    replicaCount: 2
    certmap: "cert-map-prj-polygonlabs-webapps-dev"
    image:
      repository: httpd
      tag: latest
    port: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    database: {}
    tls:
      enabled: true
      domains:
        - "test-static-webapp-2.polygon.technology"

  # - name: api-service
  #   replicaCount: 2
  #   image:
  #     repository: nginx
  #     tag: latest
  #   port: 3000
  #   resources:
  #     requests:
  #       cpu: 200m
  #       memory: 256Mi
  #     limits:
  #       cpu: 400m
  #       memory: 512Mi
  #   autoscaling:
  #     enabled: true
  #     minReplicas: 2
  #     maxReplicas: 6
  #     targetCPUUtilizationPercentage: 75
  #     targetMemoryUtilizationPercentage: 75
  #   tls: {}
  #   database: {}
  #     # enabled: true
  #     # host: "postgresql.database.svc.cluster.local"
  #     # port: 5432
  #     # name: "apidb"
  #     # secretName: "api-db-credentials"

