# values.yaml
# global:
#   environment: production
#   domain: example.com

frontend:
  namespace: frontend
  gateway:
    name: "gke-l7-global-external-managed"
    certmap: "cert-map-prj-polygonlabs-webapps-dev"
      # controllerName: "networking.gke.io/gateway-controller"
    name: "webapps-gateway"

  apps:
    - name: nginx
      replicaCount: 2
      certmap: "cert-map-prj-polygonlabs-webapps-dev"
      image:
        repository: nginx
        tag: latest
      port: 80
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      tls:
        enabled: true
        domains:
          - "test-static-webapp.polygon.technology"


backend:
  namespace: backend
  apps: []
    # - name: api-service
    #   replicaCount: 2
    #   image:
    #     repository: gcr.io/project/api
    #     tag: latest
    #   port: 8080
    #   resources:
    #     requests:
    #       cpu: 200m
    #       memory: 256Mi
    #     limits:
    #       cpu: 400m
    #       memory: 512Mi
    #   autoscaling:
    #     enabled: true
    #     minReplicas: 2
    #     maxReplicas: 6
    #     targetCPUUtilizationPercentage: 75
    #     targetMemoryUtilizationPercentage: 75
    #   database:
    #     enabled: true
    #     host: "postgresql.database.svc.cluster.local"
    #     port: 5432
    #     name: "apidb"
    #     secretName: "api-db-credentials"

    # - name: auth-service
    #   replicaCount: 2
    #   image:
    #     repository: gcr.io/project/auth
    #     tag: latest
    #   port: 9000
    #   resources:
    #     requests:
    #       cpu: 150m
    #       memory: 200Mi
    #     limits:
    #       cpu: 300m
    #       memory: 400Mi
    #   autoscaling:
    #     enabled: true
    #     minReplicas: 2
    #     maxReplicas: 4
    #     targetCPUUtilizationPercentage: 80
    #     targetMemoryUtilizationPercentage: 80

gateway:
  cert:
    name: "cert-map-prj-polygonlabs-webapps-dev"
    # controllerName: "networking.gke.io/gateway-controller"

  name: "webapps-gateway"
  namespace: frontend
