---
metadata:
  env: bali
  costCenter: agglayer

onePasswordSecrets:
  # op-reth: "vaults/myvault/items/myitem"

# Pod annotations (e.g. ad.datadoghq.com/tags for Datadog)
podAnnotations:
  config.linkerd.io/skip-inbound-ports: "8551"
# podAnnotations:
#   ad.datadoghq.com/tags: '{"network": "mynetwork"}'

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

replicaCount: 1

container:
  image:
    pullPolicy: IfNotPresent
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-reth
    tag: v1.11.5

storage:
  path: /data
  size: 500Gi

service:
  type: ClusterIP
  clusterIP: None
  authrpc:
    port: 8551
  http:
    port: 8545
  ws:
    port: 8546
  p2p:
    enabled: false
    port: 30303
  metrics:
    enabled: true
    port: 9001
  annotations: {}

httpRoutes:
  http:
    create: false
    hostname: domain.example
    gateway:
      name: gateway
      namespace: gateways

podSecurityContext: {}
securityContext: {}

genesisFileGCP:
  bucket: "bucket-name"
  object: "bucket-object"

serviceAccount:
  create: true
  automount: true
  annotations: {}

config:
  extraOptions: []

  http:
    api: admin,net,eth,web3,debug,miner

  ws:
    api: admin,net,eth,web3,debug,miner

resources:
  limits:
    memory: 16Gi
  requests:
    cpu: 2
    memory: 16Gi
