apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpcPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.websocketsPort }}
      protocol: TCP
      name: websocket
  selector:
    {{- include "rpc.selectorLabels" . | nindent 4 }}
