{{- if .Values.ingress }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.name }}-certificates
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "managedCertificateLabels" .}}
spec:
  domains:
  {{- range ((.Values.ingress).hosts) }}
  - {{ .host }}
  {{- end }}
{{- end }}