apiVersion: v1
kind: Service
metadata:
  name: {{ ((.Values.service).name) | default (printf "%s-service" .Values.name)  }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "serviceLabels" .}}
spec:
  type: {{ ((.Values.service).type) | default "NodePort" }}
  ports:
    - port: {{ ((.Values.service).port)  }}
      targetPort: {{ ((.Values.service).targetPort)  }}
      protocol: TCP
      name: http
  {{- with .Values.commonLabels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "deploymentLabels" .}}