global:
  env: bali
  podLabels:
    name: myname
    business_unit: agglayer
    role: myrole
    partner: polygon
    network: mynetwork

jumphost:
  # We only enable this in non-production environments, right? RIGHT?!?!?
  enabled: true

rpc:
  genesis: validium-bali-04-genesis.json
  image:
    repository: hermeznetwork/zkevm-node
    tag: "v0.6.1"
  replicaCount: 1
  resources:
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 1000m
      memory: 4Gi
  existingSecret: "op-secrets"

synchronizer:
  genesis: validium-bali-04-genesis.json
  image:
    repository: hermeznetwork/zkevm-node
    tag: "v0.6.1"
  replicaCount: 1
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 1Gi
  existingSecret: "op-secrets"

executor:
  image:
    repository: hermeznetwork/zkevm-prover
    tag: "v5.0.7"
  replicaCount: 1
  resources:
    limits:
      cpu: 8
      memory: 64Gi
    requests:
      cpu: 2
      memory: 16Gi
  existingSecret: "op-secrets"

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "pless"
        database: state_db
        existingSecret: "op-secrets"
        secretKeys:
          adminPasswordKey: "dbAdminPassword"
          userPasswordKey: "dbPlessPassword"
  metrics:
    enabled: true
    collectors:
      wal: false
  primary:
    extendedConfiguration: |
      max_connections = 500
    resources:
      requests:
        cpu: 4
        memory: 16Gi
    persistence:
      size: 750Gi
    initdb:
      scripts:
        00_init_event_db.sql: |
          CREATE DATABASE event_db;
          \connect event_db
          CREATE TYPE level_t AS ENUM ('emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug');
          CREATE TABLE public.event (
             id BIGSERIAL PRIMARY KEY,
             received_at timestamp WITH TIME ZONE default CURRENT_TIMESTAMP,
             ip_address inet,
             source varchar(32) not null,
             component varchar(32),
             level level_t not null,
             event_id varchar(32) not null,
             description text,
             data bytea,
             json jsonb
          );
        10_init_state_db.sql: |
          CREATE DATABASE state_db;
        20_init_pool_db.sql: |
          CREATE DATABASE pool_db;
        30_init_executor_db.sql: |
          CREATE DATABASE executor_db;
          \connect executor_db
          CREATE SCHEMA state;
          CREATE TABLE state.nodes (hash bytea PRIMARY KEY, data bytea NOT NULL);
          CREATE TABLE state.program (hash bytea PRIMARY KEY, data bytea NOT NULL);
