global:
  # tags for identifying/tracking resources
  name: foo
  host: gcp
  location: unspecified
  env: dev
  role: permissionless-node
  team: cdk
  p_service: cdk
  tag: v3

synchronizer:
  image:
    repository: hermeznetwork/zkevm-node
    tag: "v0.6.1"

executor:
  image:
    repository: hermeznetwork/zkevm-prover
    tag: "v5.0.7"

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: dookie
        username: spideyman
        password: booger
        database: state_db
  primary:
    initdb:
      scripts:
        00_init_db.sql: |
          CREATE DATABASE pool_db;
          CREATE DATABASE state_db;
          CREATE DATABASE event_db;
          CREATE DATABASE executor_db;
