apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ template "polygon-edge.genesis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/resource-policy": keep
data:
  genesis.json: {{ .Values.genesis.chainJson | mustToJson }}
