apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "polygon-edge.genesis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
subjects:
- kind: ServiceAccount
  name: {{ template "polygon-edge.genesis.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "polygon-edge.genesis.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
