apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "polygon-edge.genesis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
      #"helm.sh/resource-policy": keep
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: 
      - {{ template "polygon-edge.genesis.fullname" . }}
    verbs:  ["patch"]
