{{- if .Values.genesis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.genesis.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "polygon-edge.genesisServiceAccountName" . }}

  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
      #"helm.sh/resource-policy": keep
{{- if .Values.genesis.serviceAccount.annotations }}
  {{- range $key, $value := .Values.genesis.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "polygon-edge.labels" (dict "context" . "component" .Values.genesis.name "name" .Values.genesis.name) | nindent 4 }}
{{- end }}
