{{- $rpcHost := "" }}
{{- $rpcPort := "" }}
{{- $l1ChainID := 11155111 }}
{{- $l1NodeURL := "" }}
{{- $l1NodeURLWS := "" }}
{{- $l1RollupManagerContract := "" }}
{{- $l1GlobalExitRootContract := "" }}
{{- $datadogApiKey := "" }}
{{- $kmsKeyName := "" }}
{{- $projectId := "" }}
{{- $location := "" }}
{{- $keyring := "" }}
{{- $keyName := "" }}
{{- $keyVersion := "" }}
{{- $fullNodeRPCs := "" }}
{{- $proofSigners := "" }}

{{- $opSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.existingSecret) }}
{{- if $opSecrets.data }}
    {{- if (index $opSecrets.data "DATA_NODE_RPC_HOST") }}
        {{- $rpcHost = index $opSecrets.data "DATA_NODE_RPC_HOST" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_RPC_PORT") }}
        {{- $rpcPort = index $opSecrets.data "DATA_NODE_RPC_PORT" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_L1_CHAINID") }}
        {{- $l1ChainID = index $opSecrets.data "DATA_NODE_L1_CHAINID" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_L1_NODEURL") }}
        {{- $l1NodeURL = index $opSecrets.data "DATA_NODE_L1_NODEURL" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_L1_NODEURL_WS") }}
        {{- $l1NodeURLWS = index $opSecrets.data "DATA_NODE_L1_NODEURL_WS" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_L1_ROLLUPMANAGERCONTRACT") }}
        {{- $l1RollupManagerContract = index $opSecrets.data "DATA_NODE_L1_ROLLUPMANAGERCONTRACT" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_L1_GLOBAL_EXIT_ROOT_CONTRACT") }}
        {{- $l1GlobalExitRootContract = index $opSecrets.data "DATA_NODE_L1_GLOBAL_EXIT_ROOT_CONTRACT" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "datadog_api_key") }}
        {{- $datadogApiKey = index $opSecrets.data "datadog_api_key" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_KMSKEYNAME") }}
        {{- $kmsKeyName = index $opSecrets.data "DATA_NODE_KMSKEYNAME" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_PROJECTID") }}
        {{- $projectId = index $opSecrets.data "DATA_NODE_PROJECTID" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_LOCATION") }}
        {{- $location = index $opSecrets.data "DATA_NODE_LOCATION" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_KEYRING") }}
        {{- $keyring = index $opSecrets.data "DATA_NODE_KEYRING" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_KEYNAME") }}
        {{- $keyName = index $opSecrets.data "DATA_NODE_KEYNAME" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_KEYVERSION") }}
        {{- $keyVersion = index $opSecrets.data "DATA_NODE_KEYVERSION" | b64dec }}
    {{- end }}
    {{- if (index $opSecrets.data "DATA_NODE_PROOFSIGNERS") }}
        {{- $proofSigners = index $opSecrets.data "DATA_NODE_PROOFSIGNERS" | b64dec }}
    {{- end }}
{{- end }}

debug-mode = {{ .Values.config.debugMode }}
prover-entrypoint = {{ .Values.config.agglayerProverEndpoint | quote }}

[full-node-rpcs]
{{- range $key, $value := .Values.config.fullNodeRPCs }}
{{ $key }} = {{ $value | quote }}
{{- end }}

[proof-signers]
{{- range split "\n" $proofSigners }}
    {{- if ne . "" }}
        {{- $signer := split "," . }}
            {{ $signer._0 }}={{ $signer._1 | quote }}
    {{- end }}
{{- end }}

[rpc]
host = "0.0.0.0"
grpc-port = {{ .Values.ports.grpc }}
readrpc-port = {{ .Values.ports.readrpc }}
admin-port = {{ .Values.ports.admin }}
read-timeout = "60s"
write-timeout = "60s"
max-requests-per-ip-and-second = 5000
request-timeout = "3m"
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max_response_body_size`
# default value is equal to 10MB
max-request-body-size = {{ .Values.config.rpc.maxRequestBodySize | int }}

[grpc]
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max-encoding-message-size`
# default value is equal to 4MB
max-decoding-message-size = {{ .Values.config.grpc.maxDecodingMessageSize | int }}
max-encoding-message-size = {{ .Values.config.grpc.maxEncodingMessageSize | int }}

[prover.grpc]
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max-encoding-message-size`
# default value is equal to 4MB
max-decoding-message-size = {{ .Values.config.prover.grpc.maxDecodingMessageSize | int }}
max-encoding-message-size = {{ .Values.config.prover.grpc.maxEncodingMessageSize | int }}

[outbound.rpc.settle]
max-retries = 3
retry-interval = "7s"
confirmations = 1
settlement-timeout = "20m"
gas-multiplier-factor = {{ .Values.config.outbound.rpc.settle.gasMultiplierFactor | int }}

[log]
environment = {{ .Values.config.log.environment | quote }} # "production" or "development"
level = {{ .Values.config.log.level | quote }}
outputs = ["stderr"]
format = "json"

[auth.gcpkms]
ProjectId = {{ $projectId | quote }}
Location = {{ $location | quote }}
Keyring = {{ $keyring | quote }}
KeyName = {{ $keyName | quote }}
KeyVersion = {{ $keyVersion | atoi }}

[l1]
chain-id = {{ $l1ChainID | atoi }}
node-url = {{ $l1NodeURL | quote }}
ws-node-url = {{ $l1NodeURLWS | quote }}
max-reconnection-elapsed-time = {{ .Values.config.l1.maxReconnectionElapsedTime | quote }}
rollup-manager-contract = {{ $l1RollupManagerContract | quote }}
polygon-zkevm-global-exit-root-v2-contract = {{ $l1GlobalExitRootContract | quote }}
rpc-timeout = "45s"

[l2]
rpc-timeout = "45s"

[telemetry]
prometheus-addr = "0.0.0.0:2223"

[rate-limiting]
send-tx = "unlimited"

[rate-limiting.network]

[epoch.block-clock]
epoch-duration = {{ .Values.config.epoch.blockClock.epochDuration | int }}
genesis-block = {{ .Values.config.epoch.blockClock.genesisBlock | int }}

[shutdown]
runtime-timeout = "5s"

[certificate-orchestrator]
input-backpressure-buffer-size = 1000

[certificate-orchestrator.prover.sp1-local]

[storage]
db-path = {{ .Values.storage.path | quote }}

[storage.backup]
path = {{ .Values.backup.path | quote }}
state_max_backup_count = 100
pending_max_backup_count = 100


{{- if eq (len .Values.config.proxiedNetworks) 0 }}
[proxied-networks]
networks = [{{ join "," .Values.config.proxiedNetworks }}]
grpc-port = {{ .Values.ports.proxy }}
host = "0.0.0.0"
{{- end }}
