# templates/backend/service.yaml
{{- range .Values.backend.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.frontend.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
---
{{- end }}

# Accessible by other services using: <service-name>.<namespace>.svc.cluster.local
