env: bali

podAnnotations:
  # name: internal name of the network (e.g., bali-01)
  # project: agglayer
  # role: permissionless node, rpc, sequencer
  # partner: polygon or IP (Implementation Provider)
  # network: network name (e.g., katana)
  ad.datadoghq.com/tags: '{"name": "myname","project": "agglayer", "role": "myrole","partner": "polygon","network": "mynetwork"}'

replicas: 1

container:
  image:
    pullPolicy: IfNotPresent
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    tag: v1.9.5

# storage:
#   path: /data
#   size: 500Gi

service:
  type: ClusterIP
  clusterIP: None
  rpc:
    port: 9545
  annotations: {}

podLabels: {}
podSecurityContext: {}
securityContext: {}

existingSecret: "secretName"

config:
  l2:
    opGethAuthUrl: http://op-geth:8551

  log:
    environment: development # "production" or "development"
    level: info

  rollupJson: |
    {}

resources:
  limits:
    memory: 10Gi
  requests:
    cpu: 1
    memory: 2Gi
