env: bali

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: polygon
  network: mynetwork

replicas: 1

container:
  image:
    pullPolicy: IfNotPresent
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    tag: v1.9.5

# storage:
#   path: /data
#   size: 500Gi

service:
  type: ClusterIP
  clusterIP: None
  rpc:
    port: 9545
  annotations: {}

podSecurityContext: {}
securityContext: {}

existingSecret: "secretName"

config:
  l2:
    opGethAuthUrl: http://op-geth:8551

  log:
    environment: development # "production" or "development"
    level: info

  rollupJson: |
    {}

resources:
  limits:
    memory: 10Gi
  requests:
    cpu: 1
    memory: 2Gi
