{{- range .Values.frontend.apps }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
spec:
  parentRefs:
  - name: {{ .name }}-gateway
    sectionName: https
  hostnames:
  {{- range .tls.domains }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .name }}
      port: {{ .port }}
---
# HTTP to HTTPS redirect
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}-redirect
spec:
  parentRefs:
  - name: {{ .name }}-gateway
    sectionName: http
  hostnames:
  {{- range .tls.domains }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
{{- end }}