{{- range .Values.frontend.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  selector:
    app: {{ .name }}
---
{{- end }}
