{{- range .Values.frontend.apps }}
{{- if .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}

{{- range .Values.backend.apps }}
{{- if .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}