{{- if .Values.extraFeatures.blockscout.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polygon-edge.blockscout.fullname" . }}
  labels:
    {{- include "polygon-edge.labels" (dict "context" . "component" .Values.extraFeatures.blockscout.name "name" .Values.extraFeatures.blockscout.name) | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.extraFeatures.blockscout.image.tag | quote }}
type: Opaque
data:
  secretKeyBase: {{ randAlphaNum 64 | nospace | b64enc }}
  {{- if not .Values.extraFeatures.blockscout.database.enabled }}
  dbUrl: {{ .Values.extraFeatures.blockscout.database.external.connString | b64enc }}
  {{- else }}
  dbUrl: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.global.postgresql.auth.username .Values.global.postgresql.auth.password (include "postgresql.primary.fullname" .Subcharts.postgresql) (.Values.global.postgresql.service.ports.postgresql | int) .Values.global.postgresql.auth.database | b64enc }}
  {{- end -}}
{{- end -}}
