apiVersion: v2
name: polygon-edge
description: Helm chart to deploy Polygon Edge to a Kubernetes environment. 
version: 0.1.1
appVersion: 0.6.1
home: https://docs.polygon.technology/docs/edge/overview/
icon: https://logowik.com/content/uploads/images/t_polygon-edge8086.jpg
sources:
  - https://github.com/0xPolygon/helm-charts/charts/polygon-edge
maintainers:
  - name: epikichi
    url: https://github.com/epikichi
    email: ji@epik.dev
  - name: ZeljkoBenovic
    url: https://github.com/ZeljkoBenovic
    email: zeljko@zeljkobenovic.com
keywords:
  - polygon-edge
  - polygon
  - ethereum
  - blockchain
dependencies:
  - name: postgresql
    version: 12.1.x
    repository: https://charts.bitnami.com/bitnami
    condition: extraFeatures.blockscout.enabled, extraFeatures.blockscout.database.enabled
