{{ if .Values.config.key.useKms }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-batcher.fullname" . }}-op-signer
data:
  config.yaml: |-
    # the KMS provider to use, must be one of: GCP (default), AWS, LOCAL
    provider: GCP
    # a list of client auth configurations
    auth:
        # DNS name of the client connecting to op-signer
        # Must match the DNS name in the TLS certificate
      - name: local-client
        key: {{ .Values.config.key.path }}
        chainID: {{ .Values.config.chainId }}
        fromAddress: {{ .Values.config.key.address }}
{{ end }}
