apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-batcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "op-batcher.fullname" . }}
  selector:
    matchLabels:
      {{- include "op-batcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "op-batcher.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
        - {{ toYaml $constraint | nindent 10 | trim }}
            {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              {{- include "op-batcher.selectorLabels" $ | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "op-batcher.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              op-batcher \
                --l2-eth-rpc={{ .Values.config.l2.opGethUrl }} \
                --rollup-rpc={{ .Values.config.l2.opNodeUrl }} \
                --poll-interval=1s \
                --sub-safety-margin=6 \
                --num-confirmations=1 \
                --safe-abort-nonce-too-low-count=3 \
                --resubmission-timeout=30s \
                --rpc.addr=0.0.0.0 \
                --rpc.port={{ .Values.service.rpc.port }} \
                --rpc.enable-admin \
                --max-channel-duration=50 \
                --l1-eth-rpc="${L1_RPC_URL}" \
                --private-key="${BATCHER_PRIVATE_KEY}" \
                --log.level={{ .Values.config.log.level }} \
                --log.format={{ .Values.config.log.format }} \
                {{- range .Values.config.extraOptions }}
                --{{ . }} \
                {{- end }}
                --data-availability-type={{ .Values.config.dataAvailabilityType }}
          {{- if .Values.onePasswordSecrets }}
          envFrom:
            {{- range $name, $_ := .Values.onePasswordSecrets }}
            - secretRef:
                name: {{ $name }}
            {{- end }}
          {{- end }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpc.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
