apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peer-mgmt-service.fullname" . }}
data:
  config.yaml: |-
    log_level: info
    dry_run: false

    metrics:
      enabled: {{ .Values.config.metrics }}
      host: 0.0.0.0
      port: {{ .Values.service.metrics.port }}

    healthz:
      enabled: true
      host: 0.0.0.0
      port: {{ .Values.service.http.port }}

    poll_interval: 30s
    node_state_expiration: 1h
    rpc_timeout: 15s


    nodes:
    {{ .Values.config.nodes | toYaml | nindent 6 }}

    networks:
    {{ .Values.config.networks | toYaml | nindent 6 }}
