apiVersion: v1
kind: Service
metadata:
  name: {{ include "peer-mgmt-service.fullname" . }}
  labels:
    {{- include "peer-mgmt-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "peer-mgmt-service.selectorLabels" . | nindent 4 }}
