env: bali

podLabels:
  name: myname
  business_unit: agglayer
  role: myrole
  partner: Polygon
  network: mynetwork

replicas: 1

container:
  image:
    pullPolicy: IfNotPresent
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    tag: v1.101411.4 # https://github.com/smartcontracts/simple-optimism-node/blob/main/docker-compose.yml#L31

storage:
  path: /data
  size: 500Gi

service:
  type: ClusterIP
  clusterIP: None
  authrpc:
    port: 8551
  http:
    port: 8545
  ws:
    port: 8546
  p2pTCP:
    port: 30303
  p2pUDP:
    port: 30303
  metrics:
    port: 7300
  annotations: {}

ingress:
  create: true
  hostname: something.dev.polygon

podSecurityContext: {}
securityContext: {}

existingSecret: "secretName"

genesisFileGCP:
  bucket: "bucket-name"
  object: "bucket-object"

serviceAccount:
  create: true
  automount: true
  annotations: {}

config:
  # Sync and GC configuration
  syncmode: snap # "full" or "snap"
  gcmode: full # "full" or "archive"

  # Logging configuration
  log:
    verbosity: "3"
    format: json

  # HTTP configuration
  http:
    corsdomains: "*"
    vhosts: "*"
    addr: "0.0.0.0"
    api: admin,engine,net,eth,web3,debug,miner

  # Auth RPC configuration
  authrpc:
    addr: "0.0.0.0"
    vhosts: "*"

  # WebSocket configuration
  ws:
    addr: "0.0.0.0"
    origins: "*"
    api: admin,engine,net,eth,web3,debug,miner

  # Metrics configuration
  metrics:
    addr: "0.0.0.0"

  # P2P configuration
  p2p:
    maxpeers: "0"

  # L2 configuration
  l2:
    networkName: op-network
    sequencerHttp: http://somewhere

  # Rollup configuration
  rollup:
    halt: major
    disableTxPoolGossip: "true"

  # Cache configuration
  cache:
    database: 20 # 4GB
    gc: 12
    main: 20480 # 20GB
    snapshot: 24
    trie: 24

resources:
  limits:
    memory: 10Gi
  requests:
    cpu: 1
    memory: 2Gi
