name: Publish helm chart

on:
  push:
    branches:
      - main

jobs:
  publish-chart:
    permissions:
      contents: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v4'

    - name: Authenticate with GCP via OIDC
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/595403903631/locations/global/workloadIdentityPools/polygonlabs-shared-dev/providers/oidc-shared-dev'
        service_account: 'shared-dev-oidc-sa@prj-polygonlabs-shared-dev.iam.gserviceaccount.com'

    - name: Run helm package
      run: |
        helm package charts/permissionless-nodes

    - name: Run help push
      run: |
        helm push permissionless-nodes-0.2.0.tgz oci:europe-west2-docker.pkg.dev/prj-polygonlabs-shared-dev/polygonlabs-docker-dev
