name: Publish helm chart

on:
  push:
    branches:
      - main

env:
  # TMP: Test once on main branch with dev artifact registry
  # ARTIFACT_REGISTRY: oci:europe-west2-docker.pkg.dev/prj-polygonlabs-shared-prod/polygonlabs-docker-prod
  # OIDC_PROVIDER: projects/23849419004/locations/global/workloadIdentityPools/polygonlabs-shared-prod/providers/oidc-shared-prod
  # OIDC_SERVICE_ACCOUNT: shared-prod-oidc-sa@prj-polygonlabs-shared-prod.iam.gserviceaccount.com
  ARTIFACT_REGISTRY: oci:europe-west2-docker.pkg.dev/prj-polygonlabs-shared-dev/polygonlabs-docker-dev
  OIDC_PROVIDER: projects/595403903631/locations/global/workloadIdentityPools/polygonlabs-shared-dev/providers/oidc-shared-dev
  OIDC_SERVICE_ACCOUNT: shared-dev-oidc-sa@prj-polygonlabs-shared-dev.iam.gserviceaccount.com

permissions:
  contents: write
  id-token: write

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Authenticate with GCP via OIDC
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ env.OIDC_PROVIDER }}
        service_account: ${{ env.OIDC_SERVICE_ACCOUNT }}

    - name: Configure Artifact Registry authentication
      run: |
        echo '{"credHelpers": {"europe-west2-docker.pkg.dev": "gcloud"}}' > ~/.docker/config.json

    - name: Get list of modified charts
      id: get-modified-charts
      run: |
        CHARTS=$(git diff --name-only HEAD^ HEAD \
          | grep 'charts/.*/Chart.yaml' \
          | xargs -I{} sh -c \
            'if git diff HEAD^ HEAD {} | grep -q "version:"; then basename $(dirname {}); fi')
        echo "::set-output name=charts::$CHARTS"
    
    - name: Push helm chart
      if: steps.get-modified-charts.outputs.charts
      env:
        CHARTS: ${{ steps.get-modified-charts.outputs.charts }}
      run: |
        for chart in $CHARTS; do
          echo "Processing chart $chart"
          helm dependency update charts/$chart
          helm package charts/$chart
          helm push $chart*.tgz ${{ env.ARTIFACT_REGISTRY }}
        done
