name: Publish helm chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Authenticate with GCP via OIDC
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: projects/23849419004/locations/global/workloadIdentityPools/polygonlabs-shared-prod/providers/oidc-shared-prod
        service_account: shared-prod-oidc-sa@prj-polygonlabs-shared-prod.iam.gserviceaccount.com

    - name: Install helm dependencies
      run: |
        helm dependency update charts/permissionless-nodes

    - name: Package helm chart
      run: |
        helm package charts/permissionless-nodes

    - name: Get helm chart version
      run: |
        echo "CHART_VERSION=$(grep '^version:' charts/permissionless-nodes/Chart.yaml | awk '{print $2}')" >> $GITHUB_ENV

    - name: Push helm chart
      run: |
        helm push permissionless-nodes-$CHART_VERSION.tgz oci:europe-west2-docker.pkg.dev/prj-polygonlabs-shared-prod/polygonlabs-docker-prod
