{{- if not (eq .Values.secretsManagerConfig.type "local") }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/retention-policy": keep
{{- if .Values.secretsManagerConfig.annotations }}
  {{- range $key, $value := .Values.secretsManagerConfig.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "polygon-edge.fullname" . }}-secrets-manager-config
{{- if .Values.secretsManagerConfig.labels }}
  labels:
{{- toYaml .Values.secretsManagerConfig.labels | nindent 4 }}
{{- end }}
stringData:
  secretsManagerConfig.json: |-
    {
      "token": {{ .Values.secretsManagerConfig.vault.token | quote }},
      "server_url": {{ .Values.secretsManagerConfig.vault.serverUrl | quote }},
      "type": {{ .Values.secretsManagerConfig.type | quote }},
      "name": "<NODE_NAME>",
      "namespace": {{ .Values.secretsManagerConfig.namespace | quote }},
      "extra": {
        {{- if eq .Values.secretsManagerConfig.type "aws-ssm" }} 
        "region": {{ .Values.secretsManagerConfig.aws.region | quote }},
        "ssm-parameter-path": {{ .Values.secretsManagerConfig.aws.ssmParameterPath | quote }}
        {{- else if eq .Values.secretsManagerConfig.type "gcp-ssm" }} 
        "gcp-ssm-cred": {{ join "/" (list .Values.config.dataDir "secrets" "credentials.json") | quote }},
        "project-id": {{ .Values.secretsManagerConfig.gcp.projectId | quote }}
        {{- end }}
      }
    }
  {{- if .Values.secretsManagerConfig.vault.token }}
  vaultToken: {{ .Values.secretsManagerConfig.vault.token }} 
  {{- end }}
  {{- if .Values.secretsManagerConfig.gcp.credentialKey }}
  credentials.json: {{ .Values.secretsManagerConfig.gcp.credentialKey | mustToJson }}
  {{- end }}
{{- end }}
